### ISSUE TITLE
Flow coercing yield result without extra parens fails to parse

### ISSUE THREAD

**Issue by aaronjensen** [babel/babylon#100]
This parses:

```
function* foo(z) {
  const x = ((yield 3): any)
}
```

But this does not:

```
function* foo(z) {
  const x = (yield 3: any)
}
```

https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=true&loose=true&spec=false&code=function*%20foo(z)%20%7B%0A%20%20const%20x%20%3D%20((yield%203)%3A%20any)%0A%7D%0A%0Afunction*%20foo(z)%20%7B%0A%20%20const%20x%20%3D%20(yield%203%3A%20any)%0A%7D

The latter is parseable by flow: 

https://flowtype.org/try/#0GYVwdgxgLglg9mAVAAmHOAKAXgSmQbwChlkIEBnKZAD2QF5kMMBPGAUwBsATZAZhwBcyAIZhmOQgF9ChUJFgIUaTLgLFSFKrQYt23PkNHipQA

**Comment by nicolo-ribaudo** [comment]
Is this still a bug? In the repl it seems to work

**Comment by danez** [comment]
Yes seems this was fixed. We should add a testcase for this.

**Comment by pudility** [comment]
I have started adding some test cases 😃
