### ISSUE TITLE
Dynamic props in class body

### ISSUE THREAD

**Issue by danez** [babel/babylon#117]
> reported by imaxmaxmaximus in phabricator

The parse interprets this

```js
class Cat {

  symbol = 10
  [symbol] = 10
}
```

as

```js
class Cat {

  symbol = 10[symbol] = 10
}
```

With semicolon there is a parsing error:

```js
class Cat {

  symbol = 10;
  [symbol] = 10;
}
```

**Comment by motiz88** [comment]
Is this still the case now, with #121 merged?

**Comment by kaicataldo** [comment]
Testing locally with the current master branch, I'm still seeing a parsing error when Babylon tries to parse:
```
class Cat {

  symbol = 10;
  [symbol] = 10;
}
```
yields
```
SyntaxError: Unexpected token (2:9)
```
