### ISSUE TITLE
Improve parsing error message (T6710) 

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#119]
> Issue originally made by @markelog

Ref https://github.com/babel/babel/issues/3774

### Input code

```js
require("babylon").parse("2++");
```

### Description

Will throw a error - 

"SyntaxError: Assigning to rvalue (1:0)"

Which is pretty cryptic, parsers like esprima, or any other JS engine will show more meaningful message  - "Invalid left-hand side expression in postfix operation"

**Comment by hzoo** [comment]
Moving to https://github.com/babel/babylon/issues/119

**Comment by markelog** [comment]
Moved where?

**Comment by hzoo** [comment]
.. sigh closed this one.

**Comment by markelog** [comment]
Yey!
