### ISSUE TITLE
Parsing of a legacy octal throws Syntax Error

### ISSUE THREAD

**Issue by gabejohnson** [babel/babylon#130]
Attempting to parse `042` results in `Uncaught SyntaxError: ... Invalid number` when it evaluate to  `34`.

**Comment by loganfsmyth** [comment]
Are you setting `sourceType: 'script'`or using it in a file with `use strict`? Legacy octal syntax only works in non-strict code.

**Comment by danez** [comment]
I think this is the intended behavior.

Octals starting with a 0 are not allowed in strict mode see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Converting_mistakes_into_errors)

You need to set the `sourceType` to `"script"`, but then you probably can't use classes and import/export as they imply strict mode (http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code)

**Comment by gabejohnson** [comment]
Yep. This is my bad. I was testing a parser and my test file is a module. The token is a legacy octal.

I just forgot I was in strict mode. The workaround is `parseInt('042', 8)`.

Closing.

**Comment by loganfsmyth** [comment]
To note for anyone else coming across this, `042` is not a valid number format in strict-mode code, but you can do `0o042` which is the official specced way to write octal numbers.
