### ISSUE TITLE
Fix reserved keywords

### ISSUE THREAD

**Issue by danez** [babel/babylon#134]
http://www.ecma-international.org/ecma-262/6.0/#sec-keywords

Some throw correctly: `for`, `implements`, ...

- [x] Some don't: `enum`, `await`
- [ ] Some are supposed to be usable in script mode (non-strict) but don't: `let` (need to test other envs if this is true)

This list is probably not complete.

**Comment by kaicataldo** [comment]
I'm interested in looking at this! I have a few other commitments but can try to look at this soon. If someone else has the bandwidth right now though, please feel free to take it on.

**Comment by danez** [comment]
Awesome.
This issue contains 2 issues I think (throw for invalid identifier and the let keyword which should be usable in script mode, although not sure for the last). Feel free to only fix one of them first if its easier.

**Comment by hzlmn** [comment]
@kaicataldo is it still an issue?

**Comment by kaicataldo** [comment]
Yes! I started looking at the `let` in strict mode issue, but haven't started on the others.

**Comment by hzlmn** [comment]
@kaicataldo Can I look on `await` or `enum` ?

**Comment by kaicataldo** [comment]
@hzlmn Absolutely - don't want to be a blocker. Thanks for looking at this :)

**Comment by hzlmn** [comment]
@kaicataldo start looking here https://github.com/hzlmn/babylon/commit/2498481a511aaaf50d3f5ab61528e2d81910d486
. Can you look on this, so I will not bother with silly PRs?

**Comment by kaicataldo** [comment]
@hzlmn I recommend starting with some tests, since you know the desired result. It'll help guide what you do a lot!

**Comment by kaicataldo** [comment]
I just realized another issue I'm working on has some overlap with this one, so I should be covering the `await` portion of this task

**Comment by hzlmn** [comment]
@kaicataldo No problems, if you already done it. I am pretty new to `babylon` codebase, so even simple task like this, can take a while.

**Comment by kaicataldo** [comment]
As a quick update on the state of this issue: 

The `enum` and `await` part has been taken care of. However, the second part regarding `let` in script mode still needs to be done.

**Comment by mannanali413** [comment]
@kaicataldo is the issue with the ``` let ``` keyword resolved. If not then I can start working on it.

**Comment by kaicataldo** [comment]
@mannanali413 Please feel free!
