### ISSUE TITLE
Duplicate default error with single default

### ISSUE THREAD

**Issue by webdesserts** [babel/babylon#141]
After the updating to `babylon@6.11.2` in one of my projects I am now getting the following error in my webpack builds:

```
ERROR ./app/routes/surgery-center/patient-dashboard/procedure-search.js

Syntax error Only one default export allowed per module. (124:0)

  122 | }
  123 |
> 124 | export default connect(select)(ProcedureSearch)
      | ^
  125 |

 @ ./app/routes/surgery-center/patient-dashboard/index.js 27:0-49
 @ ./app/routes/routes.js
 @ ./app/root.js
 @ ./app/main.js
 @ multi main
```

the only exports in the file look like this

```js
//...
export class ProcedureSearch extends React.Component {
//...
}
//...
export default connect(select)(ProcedureSearch)
```

So as far as _I can tell_ there's only a single default export. Any idea what could be causing this?

Thanks for all your hard work!

**Comment by hzoo** [comment]
I can't repro with just those 2 lines? Will just need a smaller code snippet that causes the error

**Comment by webdesserts** [comment]
@hzoo kk, I'll see what I can do

**Comment by hzoo** [comment]
And this is only with babylon@6.11.2 and not 6.11.0 or 6.11.1?

**Comment by hzoo** [comment]
You should be able to do just remove lines of code in that file to find what is causing the exports error.

**Comment by webdesserts** [comment]
@hzoo kk, will try. If I shrinkwrap the project and manually bump the version around, it seems like `6.9.2` and `6.10.0` do not receive the error, while both `6.11.0`, `6.11.1`, & `6.11.2` all display the error.

**Comment by webdesserts** [comment]
@hzoo, give me a bit, I'm running into some unrelated errors that I'm trying to get around before I try to reproduce again.

**Comment by webdesserts** [comment]
@hzoo haha, fuck me. We had two similarly named files the file that the error was referencing _did actually have a duplicate export_. Babel is doing its job just fine 👍. Sorry for the scare.

**Comment by hzoo** [comment]
Ok great, glad it works then
