### ISSUE TITLE
Chinese character in JSX parse error

### ISSUE THREAD

**Issue by benjycui** [babel/babylon#151]
If I wrap Chinese character in `""`, it will be parse as `\\uxxxx`(pay attention to double slashes).

But if I wrap Chinese character in `{''}`, it is OK.

``` jsx
<Switch checkedChildren="开" unCheckedChildren={'关'} />
// Will be parse to something like this:
_react2.default.createElement(_switch2.default, { checkedChildren: '\\u5F00', unCheckedChildren: '关' })
```

**Comment by benjycui** [comment]
`babylon@6.11.2`

**Comment by danez** [comment]
I'm not entirely sure, but it seems both should be the same. Not sure though if both should be encoded or not, but the double slash seems wrong yes.

//cc @mathiasbynens

**Comment by nicolo-ribaudo** [comment]
This seems to be fixed:

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=DwZQ7glgLgxgFgAngUxga2QEwMJwgG0wCdkA7AXgCJAAfUoQFdTdUMc9CSKBvAckGdFHgF8EAegB8QA

```js
React.createElement(Switch, { checkedChildren: "\u5F00", unCheckedChildren: '关' });
```

The strings in the output still aren't the same (one is escaped, the other one isn't), but they have the same meaning.

**Comment by jridgewell** [comment]
Probably fixed in the the unicode PR. The different escaping is expected though, one's a JS string and the other is HTML escaping.
