### ISSUE TITLE
Better error message on `unexpected token` when it's because a plugin isn't turned on

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#169]
Ref https://github.com/babel/babylon/pull/163#discussion_r82658832

Example `if (!this.hasPlugin("dynamicImport")) this.unexpected();` or

```
Module build failed: SyntaxError: Unexpected token (1:6)

> 1 | import();
    |       ^
  2 |
```

If a user is using an experimental syntax and we error then we should tell them a message so it can be fixed.

We don't necessarily know they are using babel/babylon though so the error message can give some hints:
- ask the user to turn on the corresponding plugin in babylon
- ask the user to add the syntax/transform plugin in babel
- ask the user to use `parserOpts: { plugins: ['syntax'] }`

**Comment by motiz88** [comment]
Going to tackle this. I'm thinking of an `expectPlugin` helper method to replace `if (!hasPlugin(...)) unexpected()`, and maybe a small map of known Babylon plugins to Babel plugins, to support helpful messages.

**Comment by nathanhammond** [comment]
In-progress PR: https://github.com/babel/babylon/pull/178
