### ISSUE TITLE
Run a bundler (rollup/webpack)

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#181]
We don't have any dependencies so it sounds like a good idea to do now?

**Comment by DrewML** [comment]
That would be sweet - we'd avoid the cost of node's expensive module resolution algorithm.

Here is a flamechart of `babylon` parsing a single variable declarator.

![image](https://cloud.githubusercontent.com/assets/5233399/19415735/7fbbdaa2-933f-11e6-8408-4e41df01b798.png)

The time babylon takes to do the actual parsing is like ~5ms - the other 100ms is spent doing requires.

**Comment by DrewML** [comment]
One blocker to switching to `rollup`. I'm hitting a bad bug with [`rollup-watch`](https://github.com/rollup/rollup-watch), which is what we'd need to use to replace `npm run watch`. Most changes I've made, the watch starts running in an infinite loop. We probably wouldn't want to have to manually run a build after each change.

**Comment by hzoo** [comment]
We could just not run the bundle on watch - only when building/publishing although it should still run tests after the bundle on ci

**Comment by DrewML** [comment]
Cool - I can open a PR, and see if any other contributors have a huge problem with dropping `watch` (at least for now).
