### ISSUE TITLE
Conditional MemberAccess

### ISSUE THREAD

**Issue by kristofdegrave** [babel/babylon#205]
Hi,

I would like to add conditional member access to babel. This must allow developers to access the members of an object conditionally. This means they no longer need to check if the object is undefined before accessing the member of the object.

The syntax I use for this is "?." and "?[".

So before I can add a transformer for this in the babel project I need to adjust babylon so "?." and "?[" get recognized as member access but in a conditional form. I already created a [fork ](https://github.com/kristofdegrave/babylon) on which I committed some code to do the parsing and handeling.

I guess before I can create a pull request you probably want some tests added for this. This is where it is getting unclear for me. I don't know where I should add the test for this functionality. Can anyone help me with this?

I have also added the transformer on a fork of babel so you can get an idea where I want to go. https://github.com/kristofdegrave/babel/tree/master/packages/babel-plugin-transform-conditional-member-access

**Comment by SerkanSipahi** [comment]
Hi,
nice suggestion. I would use it but i think the babylon(babel) team will not add "condition member access" to babel as long as it does not have any status in:

* https://github.com/tc39/proposals/blob/master/stage-0-proposals.md
* https://github.com/tc39/proposals

I have not found any discussion about it in TC39. Maybe you could make your suggestion as proposals in TC39.

Here is an discussion about "condition member access" in https://github.com/Microsoft/TypeScript/issues/16 - maybe interesting for you!

**Comment by DrewML** [comment]
Hi @kristofdegrave,

Thanks for the interest in contributing to Babylon! @SerkanSipahi is correct that the project only accepts PRs right now for TC39 proposals that are at Stage 0 or higher. There has been [some discussion around a proposal on ESDiscuss](https://esdiscuss.org/topic/optional-chaining-aka-existential-operator-null-propagation), but nothing official yet.

It might be worth taking a look at [Sweet.js](http://sweetjs.org/), which lets you write hygienic macros for JavaScript.

**Comment by kristofdegrave** [comment]
@SerkanSipahi @DrewML Thanks for the feedback. Too bad it is not possible at the time, but let's hope it will come to es6 :). I'll leave the forks maybe sometime in the future they will become useable.

**Comment by SerkanSipahi** [comment]
@kristofdegrave "condition member access" is not part of es6.

**Comment by kristofdegrave** [comment]
It looks like what I was trying to add is already a stage 1 proposal:
https://github.com/tc39/proposals under the name Null propagation. (https://github.com/tc39/proposals at the bottom) 
Proposal: https://docs.google.com/presentation/d/11O_wIBBbZgE1bMVRJI8kGnmC6dWCBOwutbN9SWOK0fU/view#slide=id.p

Does this mean you can take this under consideration? If so can you let me know what the next steps should be for getting the PR merged?

**Comment by SerkanSipahi** [comment]
@kristofdegrave see https://github.com/babel/babylon/issues/328 ! i think they are looking for someone who can implement that.

**Comment by kristofdegrave** [comment]
Nice, working on It. ;)

**Comment by SerkanSipahi** [comment]
@kristofdegrave :)

**Comment by agudovitoria** [comment]
Hi.
¿Has been this changes released on some version, or proposed for some version?

Thank you.

**Comment by hzoo** [comment]
Check https://github.com/babel/babylon/issues/328
