### ISSUE TITLE
Unexpected token on flow function types 

### ISSUE THREAD

**Issue by mcheshkov** [babel/babylon#208]
I'm not sure if this is right place to report this issue, excuse me if I'm mistaken.

Flow correctly parse code like this (and find type error in callbacks argument), but babel don't
```js
// @flow

type Cb<T> = (mixed, ?T) => void;
type Cb0 = mixed => void;

function f(cb : Cb<number> ) : void {}

f(function(e:mixed, v:string){})
```

Without `syntax-flow` `:` is unexpected (which is expected :) )
```
Unexpected token, expected ; (3:5)
  1 | // @flow
  2 | 
> 3 | type Cb<T> = (mixed, ?T) => void;
    |      ^
  4 | type Cb0 = mixed => void;
  5 | 
  6 | function f(cb : Cb<number> ) : void {}
```

With `syntax-flow` `,` is unexpected, which is strange.
```
Unexpected token, expected ) (3:19)
  1 | // @flow
  2 | 
> 3 | type Cb<T> = (mixed, ?T) => void;
    |                    ^
  4 | type Cb0 = mixed => void;
  5 | 
  6 | function f(cb : Cb<number> ) : void {}
```

Additional parens, like `type Cb<T> = ((mixed, ?T) => void);` does not help.

**Comment by mcheshkov** [comment]
Forgot versions.
Babel 6.18.0
Flow 0.34.0

**Comment by danharper** [comment]
This is Flow 34's new "optional name" syntax. There's a PR currently open for adding support for it: #197.

Until then, continue supplying a name, e.g.

```js
// @flow

type Cb<T> = (x: mixed, y: ?T) => void;
type Cb0 = (x: mixed) => void;

function f(cb : Cb<number> ) : void {}

f(function(e:mixed, v:string){})
```

**Comment by mcheshkov** [comment]
Thanks @danharper, works nice with named arguments. Closing as duplicate.
