### ISSUE TITLE
flow annotations in function calls should be a syntax error

### ISSUE THREAD

**Issue by disnet** [babel/babylon#215]
### Input Code
```js
f(p: [])
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    plugins: ["flow"]   
}
```

### Expected Behavior

Should throw a syntax error at the `:` since that is not a valid type annotation. Note that flow itself will throw a syntax error for this code.

### Current Behavior

Outputs:

```js
f(p);
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            | 6.13.1

**Comment by danez** [comment]
closing as duplicate of #185
