### ISSUE TITLE
using "babel-template" in astexplorer

### ISSUE THREAD

**Issue by SerkanSipahi** [babel/babylon#218]
hi guys,

its possible to use `babel-template` in astexplorer?

Env - Astexplorer:
- using babylon6
- transform babelv6

**Comment by hzoo** [comment]
This is the babylon repo for the parser? I would ask this question in the https://github.com/fkling/astexplorer repo or just on slack?

<img width="672" alt="screen shot 2016-11-12 at 9 36 48 am" src="https://cloud.githubusercontent.com/assets/588473/20238524/91ee0146-a8bb-11e6-9f7a-a85c1a78a074.png">

It's part of the babel object passed into the function - just add template to the destructuring - `{ const { types, template } = babel`

**Comment by SerkanSipahi** [comment]
@hzoo Thank you for the quick response and sorry for asking in wrong repo.
