### ISSUE TITLE
Export Parser class from Babylon?

### ISSUE THREAD

**Issue by lukehorvat** [babel/babylon#22]
Can we export the Parser class from Babylon? We are already very close to doing so on [this line](https://github.com/babel/babylon/blob/b926e40/src/index.js#L20).

Then Babel plugins would be able to override Parser methods like `getTokenFromCode()` to add support for new tokens. For example, adding support for a `#` token:

```js
import * as babylon from "babylon";

babylon.tokTypes.hash = { label: "#", beforeExpr: true };

let {getTokenFromCode} = babylon.Parser.prototype;
babylon.Parser.prototype.getTokenFromCode = function(code) {
  if (code === 35) { // '#'
    ++this.state.pos;
    return this.finishToken(babylon.tokTypes.hash);
  }

  return getTokenFromCode.bind(this)(code);
};
```

At the very least, it would be nice to have some hooks into the different Parser methods.

**Comment by loganfsmyth** [comment]
See the discussion in https://github.com/babel/babylon/pull/5

For now, making parsing pluggable is something we've explicitly decided we don't want to support because it we'd then have to take the possibility of breaking existing plugins into account with any and all changes we make to Babylon.

**Comment by kittens** [comment]
What @loganfsmyth said
