### ISSUE TITLE
Better error messaging for unexpected tokens

### ISSUE THREAD

**Issue by kaicataldo** [babel/babylon#230]
Currently, when an error is thrown for an unexpected token, it looks like this: `SyntaxError: Unexpected token, expected ; (2:7)`. It looks like the error message is malformed or something is buggy in Babylon - can we make this better? Haven't looked into implementing yet, but some initial ideas:
* Just report the "unexpected token" and remove the "expected" part (Even if just this change was made, I think it would make more sense than the current output): `SyntaxError: Unexpected token (2:7)`
* Report the token that was unexpected (not sure how difficult this would be): `SyntaxError: Unexpected token foo (2:7)`

### Input Code

Not a bug, but an example of when this error is shown is:
```js
  onst foo = 1;
```

### Babylon/Babel Configuration

N/A

### Expected Behavior

To output a more complete error message. Perhaps print out which token was unexpected?

### Current Behavior

The error that currently gets thrown is `SyntaxError: Unexpected token, expected ; (2:7)`, which looks like unfinished behavior/a bug.

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  Master branch
| node             | v6.9.1
| npm              | v3.10.9
| Operating System | OSX

**Comment by danez** [comment]
This was just changed so that the `expected ;` in #150 and it is exactly what you are proposing in 2.). What do you think is buggy here?

**Comment by kaicataldo** [comment]
`Unexpected token, expected ;` is a really confusing message. Seems to me like the error message should just be `Unexpected token` in those cases where there isn't an expected value.

**Comment by kaicataldo** [comment]
Ohhhh okay, I see now. This read to me like "Unexpected token, expected <missing token value>;", but I see that `;` is the token value.

I wonder if we can make this clearer (I think it's also grammatically confusing at the moment). Thoughts on having it read something like the following? 

```
Unexpected token; expected token ";" (2:7)
```

Happy to make a PR for this if others like the idea!

**Comment by hzoo** [comment]
Yeah we can add quotes if that's more readable
