### ISSUE TITLE
flow + async + generics => SyntaxError

### ISSUE THREAD

**Issue by pavelkucera** [babel/babylon#235]
### Input Code

```js
// @flow

const test = async <T>(fn: () => T): Promise<T> => {
    return fn();
};
```

### Babylon/Babel Configuration

```js
{
  "presets": ["es2016-node5"],
  "plugins": ["transform-flow-strip-types"]
}
```

### Expected Behavior
The Flow notation is correct as far as I can tell (flow check is performed without any errors) and I expect Babel to properly strip the types

### Current Behavior
Babel reports a syntax error:
```
SyntaxError: src/async-generics.js: Unexpected token, expected ; (3:35)
  1 | // @flow
  2 | 
> 3 | const test = async <T>(fn: () => T): Promise<T> => {
    |                                    ^
  4 |     return fn();
  5 | };
  6 | 
```

And behaves correctly after removing async from the declaration.

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.14.1
| node             | 6.9.1
| npm              | 3.10.9
| Operating System | macOS

I prepared a sandbox replicating the issue at https://github.com/pavelkucera/babel-flow-async-generics-syntax-error with a travis build showing the error at https://travis-ci.org/pavelkucera/babel-flow-async-generics-syntax-error

You can see that whilst flow performs the check without any issue - https://travis-ci.org/pavelkucera/babel-flow-async-generics-syntax-error#L199
Babel fails - https://travis-ci.org/pavelkucera/babel-flow-async-generics-syntax-error#L207

Is this a bug? If so, please let me know if you need more information about the error, thank you.

**Comment by pavelkucera** [comment]
Hello, any update on this? Is it intended behaviour or a bug? Thank you.

**Comment by danez** [comment]
This is definitely a bug. Thanks for reporting. As a workaround you can use this:
```js
const test = async function<T>(fn: () => T): Promise<T> {
    return fn();
};
```

**Comment by fmoo** [comment]
I ended up using this workaround since my arrow function was autobound on an ES6 class:
```js
class Foo {
    _test = async function<T>(fn: () => T): Promise<T> {
        return fn();
    }.bind(this);
    // ...
}
```
