### ISSUE TITLE
(Discussion): Split Class/Property decorators plugin (Stage 2) from Stage 0 proposal

### ISSUE THREAD

**Issue by DrewML** [babel/babylon#237]
The `decorators` plugin currently enables support for the following proposals:

- [Class/Property decorators](http://tc39.github.io/proposal-decorators/): Stage 2
- [Method Parameter decorators](https://goo.gl/r1XT9b): Stage 0
- [Function Expression decorators](https://goo.gl/8MmCMG): Stage 0  (Don't think this is implemented yet, but may come in the future)

Is anyone opposed to breaking these out to separate plugins?

**Comment by loganfsmyth** [comment]
I didn't realize we supported function expression decorators, are you sure?

**Comment by DrewML** [comment]
> I didn't realize we supported function expression decorators, are you sure?

Updated the OP - I got that backwards. We currently supporting method param decorators, but not function expression decorators.

**Comment by danez** [comment]
If the proposals are splitted, we should also have seperate plugins I think. But we should be carefully and not break users currently using decorators already. So maybe 3 new plugins and leave the current decorator plugin as is?

**Comment by chicoxyzzy** [comment]
Please don't forget that spec still can have breaking changes so we probably need to think about naming before publish.

`babel-plugin-transform-decorators-legacy2`? 😄

**Comment by hzoo** [comment]
Ref https://github.com/babel/babel/issues/4955

- remove stage presets
- independently versioned transforms in a separate monorepo, move to main repo after es20xx
- expose parser plugins externally with a whitelist, make syntax plugins independent from babylon core.

**Comment by hzoo** [comment]
https://github.com/babel/babylon/pull/587 with the `decorators2` plugin handles Class/Property decorators: Stage 2

**Comment by hzoo** [comment]
I think decorators2 already disallows the other two so we can close this?
