### ISSUE TITLE
Generated code it is not valid (let ast = babel.template; path.node.expression.push(ast))

### ISSUE THREAD

**Issue by SerkanSipahi** [babel/babylon#244]
### Input Code
```js
@view(`Hello World`)
class Foo {
}
```

### Output Code
```js
@view( ({a: 1, b: 2, c: 3}); )
class Foo {
}
```

### Expected Behavior (no semicolon inside of @view call)
```js
@view( ({a: 1, b: 2, c: 3}) )
class Foo {
}
```

### Plugin Code
```js
export default function ({ types: t, template }) {  
  let compileTemplate = template(`({a: 1, b: 2, c: 3})`);
  return {
    visitor: {
      Decorator(path){
        let ast = compileTemplate();
        path.node.expression.arguments = []
        path.node.expression.arguments.push(ast)
      }
    }
  };
}

```

### Babylon/Babel Configuration
```js
import assert from 'assert';
import { transform } from 'babel-core';
import syntaxDecorator from 'babel-plugin-syntax-decorators';

function transformCode(code){
    let generated = transform(code, {
        plugins: [
            syntaxDecorator,
        ]
    });
    return generated.code;
}
```
### see also
see also: https://astexplorer.net/#/YD25zHTNWd/1

### Your Environment

| software         | version
| ---------------- | -------
| babylon          |  6.14.1
| babel-core          |  6.18.2
| babel-plugin-syntax-decorators | 6.13.0
| node             | 5.1.0
| npm              | 3.3.12
| Operating System | OS X El Capitan 10.11.6

**Comment by SerkanSipahi** [comment]
I resolved it with other approach:
```js
export default function ({ types: t}) {
  return {
    visitor: {
      Decorator(path){
        path.node.expression.arguments = []
        path.node.expression.arguments.push(t.identifier('{a: 1, b: 2, c:3}'))
      }
    }
  };
}
```

### Input Code
```js
@view(`Hello World`)
class Foo {
}
```

### Output Code
```js
@view({a: 1, b: 2, c: 3})
class Foo {
}
```

### Question:
1.) Is this approach ok?
2.) and is my reported issue a bug?

**Comment by loganfsmyth** [comment]
`t.identifier('{a: 1, b: 2, c:3}')` is definitely not an approach I'd recommend since an object is not an identifier and it's entirely possible that would start to throw an exception at you at some point if we add more validation.

The issue with your current code is that

    path.node.expression.arguments.push(ast);

should be

    path.node.expression.arguments.push(ast.expression);

**Comment by SerkanSipahi** [comment]
@loganfsmyth thanks this works fine for me:
```js
path.node.expression.arguments.push(ast.expression);
```
P.S. Learning never stops :)

**Comment by loganfsmyth** [comment]
`template(`({a: 1, b: 2, c: 3})`);` is just

```
template(`
    ({a: 1, b: 2, c: 3});
`);
```

with because `template` parses statements, not expressions. e.g. `ast.type === 'ExpressionStatement'`, if you want the object itself, you need to access the value of the expression statement.

**Comment by SerkanSipahi** [comment]
@loganfsmyth template contain everything. It was just an example.
