### ISSUE TITLE
Add a clearer error message for unexpected class properties

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babylon#247]
This issue comes up pretty often on SO: https://stackoverflow.com/questions/41029676/webpack-babel-loader-not-parsing-arrow-function

People always see

```
class Foo {
    prop = () => {};
}
```

throw an error and think that somehow Babel is erroring on the arrow function because they don't realize class properties are not ES6.

**Comment by hzoo** [comment]
Would this be covered by what I mention in https://github.com/babel/babylon/issues/169?

**Comment by bakkot** [comment]
I believe this was fixed by #300.
