### ISSUE TITLE
Comments inside of JSX nodes has undefined location

### ISSUE THREAD

**Issue by jlongster** [babel/babylon#248]
### Input Code

It happens when parsing comments inside of JSX:

```js
<div>{/* foo */}</div>
```

### Babylon/Babel Configuration

Not using config, using the API directly the code looks like this:

```js
const babylon = require("babylon");

var babylonOptions = {
  sourceType: 'module',
  allowImportExportEverywhere: false,
  allowReturnOutsideFunction: false,
  plugins: [
    'asyncFunctions',
    'asyncGenerators',
    'classConstructorCall',
    'classProperties',
    'decorators',
    'doExpressions',
    'exponentiationOperator',
    'exportExtensions',
    'flow',
    'functionSent',
    'functionBind',
    'jsx',
    'objectRestSpread',
    'trailingFunctionCommas'
  ]
};

console.log(require("util").inspect(
  babylon.parse("<div>{/* foo */}</div>", babylonOptions),
  { depth: 100 }
));
```

### Expected Behavior

The `JSXEmptyExpression` node should have the correct source location information.

### Current Behavior

This is the node given for the contents inside the div:

```
Node {
  type: 'JSXEmptyExpression',
  start: undefined,
  end: undefined,
  loc: SourceLocation { start: undefined, end: undefined },
  leadingComments: 
  [ { type: 'CommentBlock',
      value: ' foo ',
      start: 6,
      end: 15,
      loc: 
      SourceLocation {
        start: Position { line: 1, column: 6 },
        end: Position { line: 1, column: 15 } } } ] }
```

Notice how the `start` and `end` locations are undefined.

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.14.1
| node             | 6.9.1
| npm              | 3.10.8
| Operating System | OS X 10.11

**Comment by jlongster** [comment]
Just noticed that it happens generally with empty expressions, regardless if it has a comment or not. So parsing `<div>{}</div>` has the same bug.

**Comment by DrewML** [comment]
Looks like a regression - this worked with `Babylon` v5.8.38
