### ISSUE TITLE
provide a remediation strategy when using `export default` with `const`, `var`, or `let`

### ISSUE THREAD

**Issue by fivetanley** [babel/babylon#252]
[Babel Link](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2&experimental=false&loose=false&spec=false&code=export%20default%20const%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20return%20%60%3Cdiv%20class%3D%22foo%22%3EHI%3C%2Fdiv%3E%60%3B%0A%7D%3B%0A%0A%2F%2F%20gives%20an%20error%20like%20this%0A%0A%2F%2Frepl%3A%20Unexpected%20token%20(1%3A15)%0A%2F%2F%3E%201%20%7C%20export%20default%20const%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%2F%2F%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%0A%2F%2F%20%202%20%7C%20%20%20return%20%60%3Cdiv%20class%3D%22foo%22%3EHI%3C%2Fdiv%3E%60%3B%0A%2F%2F%20%203%20%7C%20%7D%3B%0A%0A%2F%2F%20would%20be%20sweet%20if%20the%20error%20looked%20like%20this%3A%0A%0A%2F%2Frepl%3A%20Unexpected%20token%20(1%3A15)%0A%2F%2F%20%3E%201%20%7C%20export%20default%20const%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%2F%2F%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%0A%2F%2F%20%202%20%7C%20%20%20return%20%60%3Cdiv%20class%3D%22foo%22%3EHI%3C%2Fdiv%3E%60%3B%0A%2F%2F%20%203%20%7C%20%7D%3B%0A%2F%2F%20The%20%60default%60%20export%20can%20only%20take%20an%20expression%3B%20%60const%60%20and%20%60let%60%20statements%20are%20not%20allowed.%0A%2F%2F%20You%20could%20rewrite%20it%20to%20the%20following%3A%0A%2F%2F%20const%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%2F%2F%20%20%20return%20%60%3Cdiv%20class%3D%22foo%22%3EHI%3C%2Fdiv%3E%60%3B%0A%2F%2F%20%7D%3B%0A%2F%2F%20export%20default%20MyComponent%3B&playground=true): 
### Input Code

```js
export default const MyComponent = () => {
  return `<div class="foo">HI</div>`;
};
```

### Babylon/Babel Configuration

![sketch 2](https://cloud.githubusercontent.com/assets/1275021/21087782/a13ce7ee-bfee-11e6-91c9-586481a4c1b1.png)

### Expected Behavior

`export default` only works with expressions. It would be great to get a better error message that tells you how to fix the invalid code. Something like this:

```js
//repl: Unexpected token (1:15)
// > 1 | export default const MyComponent = () => {
//    |                ^
//  2 |   return `<div class="foo">HI</div>`;
//  3 | };
// The `default` export can only take an expression; `const` and `let` statements are not allowed.
// You could rewrite it to the following:
// const MyComponent = () => {
//   return `<div class="foo">HI</div>`;
// };
// export default MyComponent;
```

### Current Behavior

Gives an error message that can be hard to understand if you're not familiar with ES2015 syntax:

```js
//repl: Unexpected token (1:15)
//> 1 | export default const MyComponent = () => {
//    |                ^
//  2 |   return `<div class="foo">HI</div>`;
//  3 | };
```

### Your Environment

Babel 6.18.2 on the babeljs.io website

**Comment by loganfsmyth** [comment]
Thanks for the suggestion, we can certainly do better here.

FYI, it's not just expressions, you can also use function and class declarations, so you could do

```
export default function MyComponent() {
    return `<div class="foo">HI</div>`;
}
```

**Comment by fivetanley** [comment]
right, this is just sort of a double take i do every time i make this mistake. it's not always with functions; there's usually some confusion around why this is valid:

```js
export const Foo = 'hi';
```

but this is not:

```js
export default const Foo = 'hi';
```

I get that it's a spec thing and dictated by TC39's spec, but i think we could help newcomers and experienced devs move past this error.

**Comment by loganfsmyth** [comment]
100% agreed :)

**Comment by hzoo** [comment]
For reference we have others labeled [polish](https://github.com/babel/babylon/labels/polish) as well.
