### ISSUE TITLE
`export default async function` parsed as FunctionExpression

### ISSUE THREAD

**Issue by daltones** [babel/babylon#257]
### Input Code
```js
export async function foo() {}
export default async function bar() {}
```
See https://astexplorer.net/#/V8ggvAMIw1

### Babylon/Babel Configuration
Experimenting on [AST explorer](https://astexplorer.net/) with babylon6-6.13.1 and all default options.

### Expected Behavior
The second line should be parsed as an `ExportDefaultDeclaration` and a `FunctionDeclaration`.

### Current Behavior
The second line is being parsed as an `ExportDefaultDeclaration` and a `FunctionExpression`.

A _named export_ with a function declaration leads to `FunctionDeclaration` whenever it's regular, async or generator function.

But a _default export_ with a function declaration leads to `FunctionDeclaration` only when it's regular or generator function. Async functions lead to `FunctionExpression`. I guess that's a bug.

**Comment by danez** [comment]
Thanks for reporting I fixed it in #324

**Comment by vjeux** [comment]
@mroch this is also an issue with flow, would be nice to get it fixed there as well :)

**Comment by danez** [comment]
The fix was reverted, due to problems.

**Comment by nicolo-ribaudo** [comment]
This works on babylon7:

https://astexplorer.net/#/gist/bd0c7fa15c96fe0553cb9961550d7ee3/latest
