### ISSUE TITLE
Wrapping a UnaryExpression and an exponential base in parentheses gives error

### ISSUE THREAD

**Issue by oskardahlberg** [babel/babylon#26]
Both expressions below produces the same error(using the babel online repl in various settings),
"Illegal expression. Wrap left hand side or entire exponentiation in parentheses."

~~~~
(-2) ** 2;
((-2) ** 2);
~~~~

According to this reference it should work,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Exponentiation

Looking briefly at the source,
https://github.com/babel/babylon/blob/8b150813f5a534e4279df25c41c37cc9dd860ebe/src/parser/expression.js#L186

My best guess is that it should also check if "left.extra.paranthesized" is false!

Cheers

**Comment by jmm** [comment]
Thanks @oskardahlberg. I [noticed that too](https://phabricator.babeljs.io/T2431#73059) and it seems like a bug to me.

**Comment by kaicataldo** [comment]
Looks like this has actually been fixed :tada: https://github.com/babel/babylon/blob/master/src/parser/expression.js#L191-L199

**Comment by danez** [comment]
Yes this was Fixed in 6.9.0
