### ISSUE TITLE
Parsing error with <= in as a computed key

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#264]
Ref https://github.com/facebookincubator/create-react-app/issues/1286

### Input Code

```js
const map = {
  [age <= 17] : 'Too young' // error on "="
};
```

http://astexplorer.net/#/g2PDLGAM14

**Comment by xtuc** [comment]
* REPL with [latest](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=&code=const%20map%20%3D%20%7B%0A%20%20%5Bage%20%3C%3D%2017%5D%20%3A%20'Too%20young'%20%2F%2F%20error%20on%20%22%3D%22%0A%7D%3B)
* REPL with [react](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=react&code=const%20map%20%3D%20%7B%0A%20%20%5Bage%20%3C%3D%2017%5D%20%3A%20'Too%20young'%20%2F%2F%20error%20on%20%22%3D%22%0A%7D%3B)

**Comment by chicoxyzzy** [comment]
> The bug seems related to the React preset.

Looks like the problem is in Flow syntax plugin

**Comment by vkurchatkin** [comment]
This is the culprit: https://github.com/babel/babylon/commit/f7c1af1c1f986c5b389faba83657d40d1eac31ae

**Comment by hzoo** [comment]
cc @danharper if you have time

**Comment by danharper** [comment]
Sure, will take a look later today!

**Comment by vkurchatkin** [comment]
Also this probably should work as well:

```js
const map = {
  [<Foo/>] : null
};
```

**Comment by vkurchatkin** [comment]
@hzoo @danharper I've made a quick patch, PTAL

**Comment by hzoo** [comment]
https://github.com/babel/babylon/issues/266 Thanks @vkurchatkin!
