### ISSUE TITLE
Output ESTree (via a plugin)

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#278]
Lots of previous discussions on this:

- https://github.com/babel/babel/issues/2769
- https://github.com/babel/babel/issues/3813#issuecomment-245406624 (where I said we would add an option)
- https://github.com/babel/babel-eslint (already does the conversion from babylon to estree+esprima to make babel compatible with eslint)
- https://github.com/babel/acorn-to-esprima - previous extracted logic.

PR is https://github.com/babel/babylon/pull/277

**Comment by danez** [comment]
react-docgen also wants to upgrade it's parser and being estree compatible would help: https://github.com/reactjs/react-docgen/pull/137
