### ISSUE TITLE
Windows-illegal characters in folder names

### ISSUE THREAD

**Issue by ryantriangles** [babel/babylon#280]
There's a folder named [test-*-option](https://github.com/babel/babylon/tree/master/test/fixtures/jsx/regression/test-*-option) at test/fixtures/js/regression. `*` is an illegal character in Windows filenames. This means that Babylon can't be installed or the repo cloned on Windows machines.

There's actually a top post on Hacker News right now about a project, [Prettier](https://github.com/jlongster/prettier), that depends on Babylon and [cannot be installed on Windows](https://github.com/jlongster/prettier-atom/issues/7) for this reason. I tried a version of Babylon with that folder renamed and that was all it took to work, so I thought I'd bring it up.

**Comment by hzoo** [comment]
This is because of https://github.com/jlongster/prettier/blob/6d6d53f6df5069765ce0a08a4a1ee9ebe38f4b83/package.json#L10 - we can just publish a new version with his fix and can use npm

**Comment by hzoo** [comment]
Basically just have to rename the folder ^ to be `test-star-option`!

**Comment by danez** [comment]
Well that was fast fixed :)
