### ISSUE TITLE
[7.0] Remove node 0.10 and 0.12 from travis

### ISSUE THREAD

**Issue by danez** [babel/babylon#282]
We are going to drop the support for node 0.10 and 0.12 in version 7.0.0 and a branch for 7.0 does already exist here https://github.com/babel/babylon/tree/7.0.

We can now safely remove node 0.10 and 0.12 from .travis.yml. Also the whole custom logic with nvm in this file can be removed. It was added because rollup only supports node 4 and up.
https://github.com/babel/babylon/blob/7.0/.travis.yml#L11-L14
https://github.com/babel/babylon/blob/7.0/.travis.yml#L20-L21

PR welcome :)

**Comment by chicoxyzzy** [comment]
What about Node 5 which is also deprecated?

**Comment by chicoxyzzy** [comment]
I think we can close this issue :)
