### ISSUE TITLE
Incorrect parsing of escaped DirectiveLiteral string

### ISSUE THREAD

**Issue by vjeux** [babel/babylon#289]
Input

```js
'\''
```

Babylon 6 value (incorrect) http://astexplorer.net/#/heginnP81D

![image](https://cloud.githubusercontent.com/assets/197597/21877651/54e5cecc-d841-11e6-91a7-0186bf4d1378.png)

Flow parser value (correct) http://astexplorer.net/#/heginnP81D/2

![image](https://cloud.githubusercontent.com/assets/197597/21877669/6dadef8e-d841-11e6-8119-96250cf68fe6.png)

**Comment by vjeux** [comment]
cc @hzoo

**Comment by DrewML** [comment]
Not saying this isn't an issue, but for the sake of prioritizing, is this something that has been hit in real code, or just a problem you spotted?

**Comment by vjeux** [comment]
I hit this in a unit test on prettier ( https://github.com/jlongster/prettier/blob/master/tests/strings/strings.js#L4 ). I don't expect it to cause trouble in real code.

**Comment by danez** [comment]
I created a PR for this, but only when using the `estree` plugin. In "normal" babel-mode the value of the `DirectiveLiteral.value` is considered to be the raw value without quotes.
