### ISSUE TITLE
[7.0] Remove `*` as a plugin option

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#296]
Not a good idea right now because spec changes and don't want to break stuff. We'll want to figure out something different. This is useful for babel-eslint/astexplorer, etc. cc @fkling 

If you look at the plugin options: https://github.com/babel/babylon#plugins

You can add them to an array like

```js
{
  plugins: ["jsx", "flow", "dynamicImport"
}
```

We thought it might be convenient for certain tools (not apps) to have an option of always getting the latest spec plugins (astexplorer.net). However I think we probably want a better way of doing this.

---

- [ ] grep for `*` in the codebase. Remove `hasPlugin('*')` type code + associated tests.

**Comment by micopc** [comment]
Hi, I'd like to work on this issue, if that's ok

**Comment by DrewML** [comment]
@micopc Perfect! It's all yours.
