### ISSUE TITLE
jsx elements in yield statement

### ISSUE THREAD

**Issue by eldereal** [babel/babylon#30]
I found that write jsx elements directly after yield statement would cause a syntax error (Unexpected token). But according to jsx spec (https://facebook.github.io/jsx/) and ECMAScript spec. JSXElement is a PrimaryExpression which can be used after yield statement.

Currently Error but should be OK:
`yield <a></a>;`

Currently OK:
`yield (<a></a>);`

Because I am writing a program heavily depends on generator functions. I want my code be more clear. So I forked this project and fix this problem in commit de56e12c6867e947cefc7e1b37676460b0365cb7. There is just one line difference where I add `{ startsExpr: true }` to `jsxTagStart` token. 

Because I am not familiar with the internal representation in this project. I don't know if it is proper to do such a change. But at least there is no test failed after change.

**Comment by kittens** [comment]
Fixed via #31.
