### ISSUE TITLE
Parse error destructuring `set` with a default value.

### ISSUE THREAD

**Issue by 10xjs** [babel/babylon#302]
When destructuring a variable `set` from an object, assigning a default value is a syntax error.

### Input Code
```js
({set = {}}) => set;
```
### Babylon/Babel Configuration
`es2015` preset

### Expected Behavior
https://astexplorer.net/#/m1RGmL6X26

### Current Behavior
https://astexplorer.net/#/uS2PFRjGwk
or
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&code=(%7Bset%20%3D%20%7B%7D%7D)%20%3D%3E%20set%3B
```
repl: Unexpected token (1:6)
> 1 | ({set = {}}) => set;
    |       ^
```

**Comment by danez** [comment]
Thanks for reporting, we will have a look soon.

**Comment by existentialism** [comment]
Fixed with https://github.com/babel/babylon/pull/317
