### ISSUE TITLE
Destructuring with spread

### ISSUE THREAD

**Issue by zertosh** [babel/babylon#311]
After a spread destructure, trailing commas or other assignments are not allowed. 

### Input Code

All of these should be syntax errors, but only some are:

```js
([...a,] = [])
([...a, b] = []) // error, OK!
const [...a,] = [] // error, OK!

({...a} = {})
({...a, b} = {})
const {...a,} = {}
const {...a, b} = {} // error, OK!
```

### Expected Behavior

Invalid syntax should not parse.

### Current Behavior

Invalid syntax parses.

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  v6.15.0
| node             | 
| npm              | 
| Operating System |

**Comment by danharper** [comment]
This is fixed in #290 for Babel 7.

It was originally fixed a while ago, but it broke React Native, so it's being held for a new major version instead.
