### ISSUE TITLE
JSXText is missing {extra: {raw}} field

### ISSUE THREAD

**Issue by vjeux** [babel/babylon#316]
```js
<div>&lt;</div>
```

only gives

```js
value: '<'
```

http://astexplorer.net/#/uslr7onHiq/1

but not `{extra: {raw}}` like we have for "StringLiteral" which is very handy.

I wonder if we could have it added? :)

**Comment by hzoo** [comment]
Actually just looked into it and found https://github.com/babel/babylon/blob/b918554d73ed20c847068243edf99d19ca146dbe/src/plugins/jsx/index.js#L407-L408

https://github.com/babel/babel/issues/2078

```js
node.extra = null;
```

**Comment by danez** [comment]
It is currently there for babel to be able to distinguish if the tokens value is escaped as js-value or xhtml-value. 

We also have another issue #271 that is related, so maybe we can find a better way to handle this.

**Comment by rattrayalex** [comment]
Related, I believe, is that `<div>&nbsp;</div>` translates to a breaking space, which @vjeux points out in [this comment](https://github.com/jlongster/prettier/issues/547#issuecomment-276811215) on the `prettier` repo, referencing [this flow ast](http://astexplorer.net/#/gist/934eef2920a039a30361f61405f98636/940581aa956466b325d7d7ca067ebd77f997deb3) compared with [this babylon ast](http://astexplorer.net/#/gist/934eef2920a039a30361f61405f98636/3cea399e6514387f497dace6fb9b51c55a69d018). 

In any case, I'm hopeful that the removal of `extra` that @hzoo mentions above is the real culprit, and worth fixing, as @danez mentioned above. Comparing [the original fix](https://github.com/babel/babel/commit/18e610820fbe82cd4314ccc65ff1cdadfe562bfd) to [the current code](https://github.com/babel/babel/blob/master/packages/babel-generator/src/generators/types.js#L147), I'm under the impression that the `node.extra = null` hack is already unnecessary. 

I'll try simply removing said hack and testing locally.

**Comment by rattrayalex** [comment]
Presumably [JSXText](https://github.com/babel/babel/blob/master/packages/babel-generator/src/generators/jsx.js#L46) should also be changed to read from `raw`, correct?

**Comment by rattrayalex** [comment]
K, I think I have this addressed between https://github.com/babel/babylon/pull/344 and https://github.com/babel/babel/pull/5256 , though I might be missing something.
