### ISSUE TITLE
[7.0] Rename flow AST Type ExistentialTypeParam to ExistsTypeAnnotation

### ISSUE THREAD

**Issue by danez** [babel/babylon#319]
Flow and babylon6 use a different node type for `*`

Example: http://astexplorer.net/#/INBlde78H0

babylon uses `ExistentialTypeParam`, whereas flow uses `ExistsTypeAnnotation`

We should change babylon and rename the node to use the same name as flow.

//cc @samwgoldman

**Comment by AvraamMavridis** [comment]
Can I take this one?

**Comment by existentialism** [comment]
@AvraamMavridis looks like @koba04 just published a PR =/ don't let that stop you from contributin on other babel/babylon issues and bugs!

**Comment by koba04** [comment]
@AvraamMavridis I'm sorry, I missed your comment.

**Comment by AvraamMavridis** [comment]
@existentialism @koba04 no worries. :)

**Comment by phpnode** [comment]
Should `NumericLiteralTypeAnnotation` also become `NumberLiteralTypeAnnotation` in line with Flow?

**Comment by danez** [comment]
@phpnode Nice catch, yes please. Do you want to make a PR based on the 7.0 branch? Otherwise I create an issue.

**Comment by koba04** [comment]
If nobody doesn't take that, I can take it.
