### ISSUE TITLE
`Unterminated string constant` error for the valid code

### ISSUE THREAD

**Issue by markelog** [babel/babylon#32]
See example - 
```js
var code = `
var multilinestring = "x\n\
#";
`

try {
  require("babylon").parse(code, { sourceType: "module" });
} catch (e) {
	console.log(e); // Error!
}

```

**Comment by loganfsmyth** [comment]
This one was not obvious to me at first either, but this isn't a Babylon issue, you're getting just what you asked for, whether it's what you intended or not :P

The backslashes in your example are never making it to Babel, they are getting processed by the template literal up front. You'd either need

```
var code = `
var multilinestring = "x\\n\\
#";
`
```

or
```
var code = String.raw`
var multilinestring = "x\n\
#";
`
```
