### ISSUE TITLE
Anonymous function or class exported as declaration

### ISSUE THREAD

**Issue by daltones** [babel/babylon#325]
### Input Code
```js
export default function () {}
// export default class {}
```
See https://astexplorer.net/#/L3YiKmr7rk

### Babylon/Babel Configuration
[AST explorer](https://astexplorer.net/) with babylon6-6.15.0 and all default options

### Expected Behavior
Exporting anonymous `function` or `class` as default should be parsed as `FunctionExpression` or `ClassExpression`.

Acorn v4.0.4 has this expected behavior.

### Current Behavior
Parsed as `FunctionDeclaration` or `ClassDeclaration`.

**Comment by hzoo** [comment]
Thanks for the report!

> Acorn v4.0.4 has this expected behavior.

It was decided to be a Declaration instead (if you check the other parsers like espree, esprima, flow, etc they are all FunctionDeclaration)

https://github.com/jquery/esprima/issues/311#issuecomment-115747292
https://github.com/estree/estree/pull/38/files

**Comment by daltones** [comment]
Hmm, sorry I didn't know that. Thanks!
