### ISSUE TITLE
Support DeclareExportDeclaration

### ISSUE THREAD

**Issue by phpnode** [babel/babylon#326]
Babylon doesn't currently support Flow's syntax for declaring ES module exports.

### Input Code

```js
declare module "something" {
  declare export var foo: string;
  declare export default {
    a: string;
    an: Object;
  };
}
```

### Expected Behavior

Need to introduce a new node type, flow uses `DeclareExportDeclaration`.

### Current Behavior
Throws a syntax error.

**Comment by danez** [comment]
There is already a issue and a PR for this. #224 #74
