### ISSUE TITLE
Fails on all TC39 early errors

### ISSUE THREAD

**Issue by zubuzon** [babel/babylon#327]
This ECMAScript parser fails on all Fails on all TC39 early errors, and mostly all TC39 tests.

**Comment by hzoo** [comment]
Thanks for reporting? I know we wanted to setup test262 - would you want to help do that? We certainly do have lots of bugs and spec-complaint issues. There's not really anything actionable here since this is too broad of an issue.

**Comment by xtuc** [comment]
See babel/babel#4987 for the test suite setup.

**Comment by hzoo** [comment]
Cool, can refer to that and we will try to make progress.

**Comment by kuraga** [comment]
Sorry about off-topic.

@zubuzon , can you **please** answer about (code of) Kewlr?.. You don't reply anywhere but I think you project is **really useful**. Thanks!

Sorry. Really.

**Comment by zubuzon** [comment]
I will break my silence :)

@hzoo Implementing such things will take a huge amount of time, and need rewrite of current code base, and you also would need a "scope tracker" to catch this errors. This is not done in one day. I have in depth experience with this process because I actually made my own ECMA parser that is 100% spec compatible. Hopefully it will be released to public by next month. A lot of code cleanup to fix, but everything passes. And in the development process I also discovered that Babylon parses tests that is invalid when it comes to specs. This you will see if you try to parse many of the other TC39 tests - not only early-errors.

@kuraga Kewlr has nothing to do with a Ecma parser. That script does what it say it should do.

**Comment by zubuzon** [comment]
@hzoo If I'm not mistaken, only usecase of Babylon is Babel? So the question would also be if it's needed to cover the specs 100%. That *almost* all `TC39-262` `pass` and `pass-explicit` tests should pass, I take for granted. I choose to say *allmost* because if you deep dive into this, you will be surprised to learn that some of the `TC39-262` tests itself violating the specs.

But once again. This will take a huge amount of time to fix.
