### ISSUE TITLE
Optional Chaining: Stage 1

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#328]
TC39 Proposals: https://github.com/tc39/proposals

Stage: 1, Gabriel Isenberg, Claude Pache

Proposed at TC39 Meeting: https://github.com/tc39/agendas/blob/master/2017/01.md#agenda-items
Spec Repo: https://github.com/tc39/proposal-optional-chaining
Slides: https://docs.google.com/presentation/d/11O_wIBBbZgE1bMVRJI8kGnmC6dWCBOwutbN9SWOK0fU/edit#slide=id.p

ESTree Issue to discuss AST Spec: https://github.com/estree/estree/issues/146

cc @gisenberg if you can implement or work with someone to do so. (Please join our slack if you haven't http://slack.babeljs.io/)

--- 
Babylon PR: https://github.com/babel/babylon/issues/545
Babel PR: https://github.com/babel/babel/pull/5786

**Comment by gisenberg** [comment]
Thanks for looping me in! I wanted to let everyone know that I'm over in the BabelJS Slack if there are others that would like to discuss this feature further. I'm currently working with @bmeck on the Babel side of things.

**Comment by kristofdegrave** [comment]
I'm currently werking on An PR for this

**Comment by sunnylqm** [comment]
Any news? @kristofdegrave

**Comment by rattrayalex** [comment]
As discussed in the babel slack, I'm also interested in contributing to this once the spec is a bit more settled. 

I previously implemented a `?.` feature for [LightScript](http://www.lightscript.org) (a fork/superset of JS built on babylon/babel). In case it helps anyone, here is: 

- The [babel transform](https://github.com/lightscript/babel-plugin-lightscript/blob/master/src/index.js#L932) which implements short-circuiting. 
- The [associated tests](https://github.com/lightscript/babel-plugin-lightscript/tree/master/test/fixtures/safe-member-expression)
- The [commit](https://github.com/lightscript/babylon-lightscript/commit/f59a365f1746e7a541fb29bcb82e7d770f186fb3) adding the feature to the lightscript parser (a fork of babylon). It uses poor naming ("elvis operator" isn't accurate) and isn't backwards-compatible; a different approach would be necessary. 

My version doesn't currently support assignments or delete, though I may add those soon.

**Comment by cusspvz** [comment]
Can't wait to see this on ES. Inspite of it being yet at `stage-1`, it is the only thing that I've always wanted to be part of EcmaScript since I stopped using CoffeeScript. I wish I had spare time to implement it.

**Comment by thomaschaaf** [comment]
@gisenberg @kristofdegrave is this still something you are working on? Do you need help?

**Comment by xtuc** [comment]
Based on @kristofdegrave's work, I can make a PR with this https://github.com/babel/babylon/compare/master...xtuc:feat-optional-chaining

I have the Babel part as well https://github.com/babel/babel/compare/7.0...xtuc:feat-optionnal-chaining

I currently only support the basic syntax:

```js
a?.b = 42
delete a?.b
foo?.bar()
```

**Comment by gisenberg** [comment]
@thomaschaaf This is still underway. If you're interested in helping, https://github.com/gisenberg/proposal-optional-chaining is tracking the remaining work. I'm also in the BabelJS Slack if you want to reach out directly.

**Comment by hzoo** [comment]
@xtuc, @kristofdegrave  Let's start the PR so we can make a review by us + Gabe?

**Comment by hzoo** [comment]
The babylon PR is merged (https://github.com/babel/babylon/issues/545)

Please help review/test https://github.com/babel/babel/pull/5786

**Comment by littledan** [comment]
For context, at the TC39 meeting where this proposal was presented, there were a couple concerns raised about the scope of the proposal, one syntactic and one semantic. I've filed [two](https://github.com/tc39/proposal-optional-chaining/issues/4) [issues](https://github.com/tc39/proposal-optional-chaining/issues/3) to discuss these issues. This is a Stage 1 feature and subject to change!

**Comment by sunnylqm** [comment]
https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-optional-chaining
