### ISSUE TITLE
[7.0] Rename flow AST Type NumericLiteralTypeAnnotation to NumberLiteralTypeAnnotation

### ISSUE THREAD

**Issue by danez** [babel/babylon#329]
Flow and babylon6 use a different node type for the following typeAnnotation:

```js

var a : 1 = 1;
```

babylon uses NumericLiteralTypeAnnotation, whereas flow uses NumberLiteralTypeAnnotation

We should change babylon and rename the node to use the same name as flow.

**Comment by danez** [comment]
We also need to do this change in babel itself. See https://github.com/babel/babel/pull/5199 as a reference.

**Comment by hzoo** [comment]
Done in https://github.com/babel/babel/issues/5229
