### ISSUE TITLE
Decorators on computed class method names

### ISSUE THREAD

**Issue by leonid-bauxy** [babel/babylon#33]
I propose that support for decorators on computed properties is added to `babylon`.

It was suggested in `babel-eslint` repo, that I open an issue here.
Related issue: https://github.com/babel/babel-eslint/issues/309.

This doesn't work right now:

``` js
  @autobind
  [method](arg) {
      // do something
  }
```

**Comment by hzoo** [comment]
This is handled then https://github.com/babel/babylon/pull/587 and will be in the next beta release which should be 7.0.0-beta.15 (soon)
