### ISSUE TITLE
[Flow] Add support for method boolean on FunctionTypeAnnotation

### ISSUE THREAD

**Issue by vjeux** [babel/babylon#331]
Right now,

```js
type T = { method: () => void };
type T = { method(): void };
```

produce the exact same AST (and behave the same way). It would be nice to differentiate somehow so that we can print them the way they were written.

The flow parser is going to get a `method` boolean on `FunctionTypeAnnotation` that distinguishes between the two forms.

It would be great to have the same for Babylon so we can keep the printer simple!

Thanks!

cc @hzoo @samwgoldman

**Comment by samwgoldman** [comment]
Yup, `method` property on the object type ast, like we have for object values, sounds good to me.

**Comment by danharper** [comment]
I've got a PR open now for this (#334), adding `method` to `FunctionTypeAnnotation`.

How about for `ObjectTypeCallProperty` which also contains a method-looking `FunctionTypeAnnotation`, e.g. `type T = { (): number }`?

**Comment by phpnode** [comment]
@danharper `ObjectTypeCallProperty` is always a method, I don't think it's necessary there.
