### ISSUE TITLE
Exponentiation operator error with negative base

### ISSUE THREAD

**Issue by mroch** [babel/babylon#34]
Trying to parse `((-1) ** 2);` fails with the following error, despite already being wrapped in parens:

```
Illegal expression. Wrap left hand side or entire exponentiation in parentheses. (1:3)
> 1 | ((-1) ** 2);
    |    ^
```

**Comment by mroch** [comment]
both Firefox 49 nightly and Traceur parse `-1 ** 2` without requiring parens (despite what [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Exponentiation) says should happen).

**Comment by jmm** [comment]
Thanks @mroch -- I think this is the same as https://github.com/babel/babylon/issues/26 though? (Maybe that could use a better title?)

**Comment by mroch** [comment]
indeed, not sure why i didn't see that
