### ISSUE TITLE
sourceType: template

### ISSUE THREAD

**Issue by thejameskyle** [babel/babylon#343]
Right now we have a couple of options which enable invalid syntax like:

- `allowImportExportEverywhere`
- `allowReturnOutsideFunction`
- `allowSuperOutsideMethod`

And I was about to add another one in #341.

These are primarily meant for use cases like `babel-template` where we allow invalid syntax because it's meant for constructing a final AST.

Instead of adding more options like this I would like to propose a third `sourceType` called `"template"` which will solve the use case more thoroughly.

Here's an exhaustive list of every `raise()`-d error and if I think it should be disabled in template mode:

**parser/expression.js**

- [ ] [Redefinition of `__proto__` property](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L40) `({ __proto__: 1, __proto__: 2 })`
- [ ] [You're trying to assign to a parenthesized expression](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L129) `({a}) = 2;`
- [ ] [Illegal expression. Wrap left hand side or entire exponentiation in parentheses.](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L200) `-5 ** 6;`
- [ ] [Deleting local variable in strict mode](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L239) `(function () { 'use strict'; delete i; }())`
- [x] [import() requires exactly one argument](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L308) `import();`
- [x] ['super' outside of function or class](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L386) `super`
- [ ] [super() outside of class constructor](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L395) `class A {x () {super()}}`
- [x] [Binding should be performed on object property.](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L519) `::foo`
- [x] [The only valid meta property for new is x.y](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L542) `new.prop`
- [ ] [You have trailing decorators with no property](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L802) `({ @bar });` (tokenizer won't let you get here)
- [ ] [getter should have no params](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L829) `({ get prop(x) {} })`
- [x] [setter should have exactly one param](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L831) `({ set prop() {} })`
- [ ] [Binding yield in strict mode](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L981) `"use strict"; (yield) => 42`
- [ ] [Non-simple parameter in strict mode](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L993) `function (a = "default") {"use strict";}`
- [ ] [invalid use of await inside of an async function](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L1056) `(async function() { await.foo; })` (I think? Tokenizer doesn't let you end up here)
- [ ] [x is a reserved word](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L1067) `const { enum } = foo();`
- [ ] [x is a reserved word in strict mode](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L1071) `function eval() {'use strict'; }`
- [ ] [await* has been removed from the async functions proposal. Use Promise.all() instead.](https://github.com/babel/babylon/blob/master/src/parser/expression.js#L1083) `(async function() { await* foo(); })`

**parser/lval.js**

- [ ] [Object pattern can't contain getter or setter](https://github.com/babel/babylon/blob/b918554d73ed20c847068243edf99d19ca146dbe/src/parser/lval.js#L23) `( { get x() {} } ) = 0`
- [ ] [Object pattern can't contain methods](https://github.com/babel/babylon/blob/b918554d73ed20c847068243edf99d19ca146dbe/src/parser/lval.js#L25) `({a(){}})=0`
- [ ] [Only '=' operator can be used for specifying default value.](https://github.com/babel/babylon/blob/b918554d73ed20c847068243edf99d19ca146dbe/src/parser/lval.js#L51) `([a += a] = a)`
- [ ] [Invalid left-hand side (in x/expression)](https://github.com/babel/babylon/blob/master/src/parser/lval.js#L61) `3 = 4`
- [ ] [Argument name clash in strict mode](https://github.com/babel/babylon/blob/master/src/parser/lval.js#L221) `function a(t, t) { "use strict"; }`
- [ ] [Binding/Assigning to member expression](https://github.com/babel/babylon/blob/master/src/parser/lval.js#L229) (idk)
- [ ] [(Binding invalid/Invalid) left-hand side (in x/expression)](https://github.com/babel/babylon/blob/master/src/parser/lval.js#L261) `3 = 4`

**parser/statement.js**

- [ ] ['import' and 'export' may only appear at the top level](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L105) `if (1) import "x";`
- [x] ['import' and 'export' may appear only with 'sourceType: module'](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L109) `import "x";`
- [x] [Leading decorators must be attached to a class declaration](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L161) `@foo`
- [x] [Unsyntactic (break/continue)](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L198) `break;`
- [x] ['return' outside of function](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L294) `return;`
- [ ] [Multiple default clauses](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L335) `switch (x) { default: {}; default: {}; }`
- [ ] [Illegal newline after throw](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L357) `throw\n10;`
- [x] [Missing catch or finally clause](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L390) `try { }`
- [ ] ['with' in strict mode](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L413) `(function () { 'use strict'; with (i); }())`
- [ ] [Label x is already declared](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L428) `x: while (true) { x: while (true) { } }`
- [ ] [Octal literal in strict mode](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L497) `function hello() { 'use strict'; "\1"; }`
- [ ] [Complex binding patterns require an initialization value](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L562)`let [x]`
- [ ] [Duplicate constructor in the same class](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L719) `class A { constructor() {} 'constructor'() }`
- [ ] [Constructor can't have get/set modifier](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L720) `class A { get constructor() {} }`
- [ ] [Constructor can't be a generator](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L721) `class A { *constructor() {} }`
- [ ] [Constructor can't be an async function](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L722) `class A { async constructor() {} }`
- [ ] [Classes may not have static property named prototype](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L733) `class A { static prototype() {} }`
- [ ] [Duplicate constructor call in the same class](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L739) `class A { call constructor() {} call constructor() {} }`
- [ ] [You can't attach decorators to a class constructor](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L746) `class A { @foo constructor() {} }`
- [ ] [You have trailing decorators with no method](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L757) `class Foo { @foo }`
- [ ] [You can only use Class Properties when the 'classProperties' plugin is enabled.](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L768) `class Foo { bar = 'bizz'; }` (tokenizer prevents)
- [ ] [You can only use decorators on an export when exporting a class](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L940) `@bar export function foo() {}`
- [ ] [Only one default export allowed per module./x has already been exported. Exported identifiers must be unique.](https://github.com/babel/babylon/blob/master/src/parser/statement.js#L974) `export default foo; export default foo;`

There are two categories:
- Errors caused by syntax that needs to be wrapped in other syntax (i.e. `return;` – can be put inside function)
  - Not syntax which is invalid due to being wrapped in other syntax (i.e. `({a}) = 2;` – would have to be unwrapped)
- Errors caused by syntax that is missing a child node (i.e. `try {}` – `catch {}` can be added programmatically)
  - Not when missing a parent node, isn't useful/possible (i.e. `class { @foo }` – you can't attach the decorator to a method afterwards)

These are pretty well defined constraints which could even be codified into how exceptions are raised if we categorized everything (I don't want to do that because it's just a ton of bike-shedding with no obvious benefit).

Also, we should deprecate these afterwards:

- `allowReturnOutsideFunction`
- `allowSuperOutsideMethod`

**Comment by danez** [comment]
Wow, that's an extensive list. 
We can also disable more staff later, if needed.

I really like this idea instead of the options. Do you want to work on this yourself or should we label it as `help wanted`?
