### ISSUE TITLE
[7.0] Change ForAwaitStatement node type to match ESTree

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#348]
Ref https://github.com/estree/estree/pull/138

> Change to be `ForOfStatement with property "await": true`

Original PR: https://github.com/babel/babylon/pull/17

---
- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babylon/blob/master/CONTRIBUTING.md)
- [ ] Check you are on 7.0 branch with `git checkout 7.0` and then make a branch off of that to PR
- [ ] modify spec.md doc (table of contents + entry) https://github.com/babel/babylon/blob/master/ast/spec.md#forawaitstatement
- [ ] modify node type https://github.com/babel/babylon/blob/898c4a7623787795c35b57ce119b4fd1a29d1766/src/parser/statement.js#L536
- [ ] fix test fixtures

**Comment by aweary** [comment]
@hzoo mind if I give this one a shot? 😃

**Comment by hzoo** [comment]
sure go ahead 🙂, and join our slack if you haven't already

**Comment by hzoo** [comment]
Done in https://github.com/babel/babylon/issues/349
