### ISSUE TITLE
class extends null error

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [babel/babylon#35]
Error: 'this' is not allowed before super()

```javascript
class Class extends null {
    constructor(name) {
        this.name = name
    }
}
```

Babel must not be throw error if we access to `this` without `super()` if parent class is null.
Null parent class hasn't constructor, an obvious logical fallacy.

Temporary hack:
```javascript
class NullClass extends null {

}

class Class extends NullClass {
    constructor(name) {
        super()
        this.name = name
    }
}
```

**Comment by uMaxmaxmaximus** [comment]
P.S. where babel issues tracker???? I was forced to write here

**Comment by hzoo** [comment]
https://phabricator.babeljs.io/ - it's on the readme https://github.com/babel/babel#want-to-report-a-bug-or-request-a-feature

**Comment by uMaxmaxmaximus** [comment]
omg i no understand, github has issues tracker. a not want lern another tracker. a will be report bugs there

**Comment by kittens** [comment]
@uMaxmaxmaximus don't report bugs then
