### ISSUE TITLE
Token value undefined

### ISSUE THREAD

**Issue by sotream** [babel/babylon#356]
### Input Code
I've created [demo repository](https://github.com/sotream/babylon_test), please check it. 

### Expected Behavior
Files should be identical in src and in dest folders.

### Current Behavior
Brackets around JSX disappear.

Part of AST:
```
  Token {
       type: [Object],
       value: undefined,
       start: 449,
       end: 450,
       loc: [Object] 
  },
```

### Your Environment

| software         | version
| ---------------- | -------
| Babylon       | 6.15.0
| node            |7.5.0
| npm             | 4.1.2 
| Operating System | Ubuntu gnome 16.04

**Comment by loganfsmyth** [comment]
I'm not sure I understand your comment about the token, but I can say that the lack of parens is expected. They are not needed.

**Comment by sotream** [comment]
@loganfsmyth Maybe you are right :) But according to astexplorer online parser it can be there.

**Comment by loganfsmyth** [comment]
ASTExplorer is currently configured to use a different parser configuration than standard Babel: https://github.com/fkling/astexplorer/pull/161

cc @hzoo

**Comment by sotream** [comment]
@loganfsmyth I know. I've looked into source code of astexplorer. By the way thanks for your answer.

**Comment by loganfsmyth** [comment]
Gotcha, yeah `recast` attempts to preserve formatting but `babel-generator` does not, so that is why you see different behavior for this example.

**Comment by danez** [comment]
This is not problem with babylon as babylon correctly has parentheses information on the node.
