### ISSUE TITLE
Decorators on nested classes attach to wrong class

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babylon#357]
### Input Code

```js
@id
export default class Sample {
  method() {
    class Child {}
  }
}
```

### Babylon/Babel Configuration

```js
{
  "plugins": ["decorators"],
}
```

### Expected Behavior
Should output an AST with the `decorators` property attached to the outer `Sample` class.

### Current Behavior
Outputs an AST with the `decorators` property attached to the `Child` class instead.

I'm assuming we're not clearing and then restoring the tracked `decorators` state when entering a nested class declaration.

**Comment by xtuc** [comment]
Isn't it the same as #259?

**Comment by loganfsmyth** [comment]
Ah definitely is, not sure how I missed that.
