### ISSUE TITLE
[7.0] Flow and Babylon produce invalid AST nodes for `(z: typeof X)` syntax

### ISSUE THREAD

**Issue by phpnode** [babel/babylon#359]
When using flow's `typeof X` syntax to annotate a type both Babylon and Flow produce incorrect AST nodes for the argument of the annotation. If X is an identifier that corresponds to a Flow type name, Flow will use the type name instead, so `(b: typeof string)` produces a `StringTypeAnnotation` rather than a `GenericTypeAnnotation<'string'>`. This also applies to member expressions, e.g. `(z: typeof z.y)` produces `QualifiedTypeIdentifier` rather than `MemberExpression`. 

Since there seems to be an effort to clean up the Flow AST types for 7.0 I'm hoping this one can be tackled too. Please see these issues on Flow - facebook/flow#2682 and facebook/flow#3055 

### Input Code

```js
const bool = true;
const b: typeof bool = true; // TypeofTypeAnnotation<BooleanTypeAnnotation>

const x = {y: 123};
const z: typeof x.y = 123; // TypeofTypeAnnotation<QualifiedTypeIdentifier>
```

### Expected Behavior

Flow and Babylon should treat these as `GenericTypeAnnotation`s, and either `GenericTypeAnnotation` should be expanded to allow a `MemberExpression` in the `id` or a new node type should be added which can cover this case, e.g. `ExpressionTypeAnnotation`.
```js
const bool = true;
const b: typeof bool = true; // TypeofTypeAnnotation<GenericTypeAnnotation<'bool'>>

const x = {y: 123};
const z: typeof x.y = 123; // TypeofTypeAnnotation<ExpressionTypeAnnotation>
```

**Comment by danez** [comment]
We are waiting for flow to fix this, before we start with this.
