### ISSUE TITLE
Incorrect parsing of Flow annotations with generics inside JSX

### ISSUE THREAD

**Issue by mroch** [babel/babylon#36]
```
let foo = <bar x={function(x): Array<string> {}} />;
```

fails to parse (as of babylon-6.7.0: [astexplorer](http://astexplorer.net/#/eA6Une7ryK/1)), saying the `/` is unexpected.

wrapping `Array<string>` in parens parses correctly.

**Comment by kittens** [comment]
Found it, due to some weird context issues with identifying whether `{` is a statement or expression.
