### ISSUE TITLE
Parses invalid Async arrow with await

### ISSUE THREAD

**Issue by ghost** [babel/babylon#362]
### Input Code

```js
   parse(async(x = await) => {  })
```

### Babylon/Babel Configuration

```js
var babylon = require('babylon').parse;
```

### Expected Behavior

According to the specs, this should throw an syntax error. Esprima throws on it, but Acorn and Babylon does not.

### Current Behavior

Parses just fine

**Comment by danez** [comment]
This correctly throws in the latest version of babylon 6.17.2
