### ISSUE TITLE
6.16.0 releases is buggy - Please take a look

### ISSUE THREAD

**Issue by idancali** [babel/babylon#373]
[Related](https://github.com/facebook/react-native/issues/12542)

**Comment by hzoo** [comment]
Thanks for the report, we'll be looking into it shortly

**Comment by hzoo** [comment]
Releasing v6.16.1 until we actually get the time to figure this out.

**Comment by danez** [comment]
There is now an open PR for react-native.
https://github.com/facebook/react-native/pull/12550
with 7.0 we reintroduced the change that was breaking react-native.
