### ISSUE TITLE
Parsing yield + dynamicImport

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#378]
Ref https://github.com/babel/babel-preset-env/issues/168

I believe preset-env -> async-to-gen and it fails to parse

Seems like this doesn't parse: http://astexplorer.net/#/gist/d793e984f4ccfe0ca80c3760490c2fc2/62f92b3ed7628599ad98e884a7e3c1ee25344798

```js
function* a() {
  yield import('http');
}
```

@kesne

**Comment by kesne** [comment]
This is also tracked in webpack, for the acorn plugin that's here: https://github.com/kesne/acorn-dynamic-import

Probably should knock both out at once, most people using `import()` in webpack use `babel-eslint`, so having them match would be :100:

**Comment by hzoo** [comment]
Also made https://github.com/webpack/webpack/pull/4308 btw

**Comment by kesne** [comment]
Webpack will be fixed with this: https://github.com/kesne/acorn-dynamic-import/pull/5
