### ISSUE TITLE
Linebreak after await keyword leads to 'unexpected token'

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#38]
From https://phabricator.babeljs.io/T7378

Example
```js
async function a() {
 await
 1;
}
```

http://astexplorer.net/#/Wq8Hq7MjF0

or is that correct?

**Comment by hzoo** [comment]
Actually looking at 

https://github.com/tc39/ecmascript-asyncawait/blob/cdc8e3c567e47fb73ee2360be3faac636752b164/spec/syntax.html#L3-L12

looks like it's correct?

**Comment by loganfsmyth** [comment]
There's no line terminator allowed between `async` and `function`, but it doesn't look like there is a restriction between `await` and it's expression. I assume because the expression is required, whereas with `yield` it is required.

**Comment by hzoo** [comment]
Ok lol how did I read that wrong..
