### ISSUE TITLE
Unable to import babylon using es6 import syntax

### ISSUE THREAD

**Issue by u9520107** [babel/babylon#387]
Unable to import babylon using es6 import syntax.

### Input Code

```js
import babylon from 'babylon';
console.log(babylon); // => undefined
```

### Babylon/Babel Configuration

```js
{
  "presets": [ "es2015", "stage-0"],
  "plugins": [
    "transform-runtime"
  ]
}
```

### Expected Behavior

Babylon should be able to be imported with es6 syntax.

### Current Behavior

Imported variable would be undefined. If using requrie('babylon') then things would work as expected.
I checked in node_modules/babylon/lib/index.js, and found that __esModule has been set to true, while the exported object doesn't follow es6 module structure (module was not assigned as the default property). Simply removing the Object.defineProperty call to set __esModule to true should suffice to fix this issue?

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.16.1
| node             |  7.2.0
| npm              |  yarn 0.19.1
| Operating System |  Windows 10

**Comment by xtuc** [comment]
Babylon does not have a default export. You can direcly use the parse function with:

```js
import {parse} from 'babylon';
console.log(parse); // => Function
```

**Comment by u9520107** [comment]
Ahh.. ok. Thanks!

**Comment by xtuc** [comment]
If it's ok for you can I close this issue? Feel free to reopen it if needed.

**Comment by u9520107** [comment]
It's good, I should've realized to use named imports in the first place.
