### ISSUE TITLE
Document deviations from ESTree spec

### ISSUE THREAD

**Issue by nene** [babel/babylon#40]
I tried using Babylon parser as a replacement for Esprima, discovering that the AST it produces doesn't quite correspond to the [ESTree spec](https://github.com/estree/estree). Which is even more surprising because the README states that Babylon is based on acorn, which does conform to ESTree spec.

I found no documentation about this. So far I've discovered the following differences:

- [Literal][] token is replaced with [StringLiteral][], [NumericLiteral][], [BooleanLiteral][], [NullLiteral][], [RegExpLiteral][]
- [Property][] token is replaced with [ObjectProperty][] and [ObjectMethod][]
- [MethodDefinition][] is replaced with [ClassMethod][]
- what else?

I'd like to evaluate whether it's feasible for me to switch the parser to Babylon... but I'm not really sure how big the AST differences turn out to be.

[Literal]: https://github.com/estree/estree/blob/master/spec.md#literal
[Property]: https://github.com/estree/estree/blob/master/spec.md#property
[MethodDefinition]: https://github.com/estree/estree/blob/master/es6.md#methoddefinition

[StringLiteral]: https://github.com/babel/babel/blob/master/doc/ast/spec.md#stringliteral
[NumericLiteral]: https://github.com/babel/babel/blob/master/doc/ast/spec.md#numericliteral
[BooleanLiteral]: https://github.com/babel/babel/blob/master/doc/ast/spec.md#booleanliteral
[NullLiteral]: https://github.com/babel/babel/blob/master/doc/ast/spec.md#nullliteral
[RegExpLiteral]: https://github.com/babel/babel/blob/master/doc/ast/spec.md#regexpliteral
[ObjectProperty]: https://github.com/babel/babel/blob/master/doc/ast/spec.md#objectproperty
[ObjectMethod]: https://github.com/babel/babel/blob/master/doc/ast/spec.md#objectmethod
[ClassMethod]: https://github.com/babel/babel/blob/master/doc/ast/spec.md#classmethod

**Comment by loganfsmyth** [comment]
Not really a direct answer, but FYI Babel's AST format is documented here: https://github.com/babel/babel/blob/master/doc/ast/spec.md. We should probably move that to this repo though.

Babel's format is based on Acorn, but does not attempt to correspond directly with ESTree.

**Comment by nene** [comment]
Thanks for the reference.

I also noticed, that AST for JSX contains a node called `JSXText`, which deviates from [JSX AST documented by facebook](https://github.com/facebook/jsx/blob/master/AST.md). But Babel AST docs for JSX and Flow are empty files: https://github.com/babel/babel/tree/master/doc/ast

**Comment by jmm** [comment]
Another one is directives. In ESTree they're just `ExpressionStatement`s in `Program.body`. In Babel 6 there's `Directive` and `DirectiveLiteral` and `Program.directives`. I wonder how many people would be interested in this documentation. I'm not sure anyone would maintain it, so I wonder if it'd make more sense as a wiki. I don't know that the AST spec would change much either though.

**Comment by kittens** [comment]
Closed via #41.
