### ISSUE TITLE
Un-popped push

### ISSUE THREAD

**Issue by andy-ms** [babel/babylon#404]
In the `src/plugins/flow.js` [override](https://github.com/babel/babylon/blob/7a6d495704d4d86189ef13195ad3115cca8f5bbc/src/plugins/flow.js#L1375) of `parseMaybeAssign`, there is a call to `this.state.context.push()`, followed by a block of code, followed by a call to `this.state.context.pop()`.
But there is an early return inside that block of code, meaning that the push may not be popped. This looks incorrect, but naively fixing it by adding a `pop()` before the early `return` breaks some tests.

**Comment by hzoo** [comment]
Hey @andy-ms! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
