### ISSUE TITLE
Tighten up parsing of Flow TypeCasts

### ISSUE THREAD

**Issue by DrewML** [babel/babylon#413]
### Input Code

```js
state.set('foo': bar)
```

### Babylon/Babel Configuration

Flow syntax plugin enabled

### Expected Behavior
Should be a syntax error

### Current Behavior
We're currently parsing `bar` as a TypeCastExpression w/ a value of `foo`. Flow requires that you wrap a TypeCastExpression in parens, and we're allowing the parens for the CallExpression to be used right now, which the Flow parser does _not_ allow.

Context: https://twitter.com/schep_/status/841741581589860355

**Comment by dschep** [comment]
Thanks for pointing out this is actually even a bug if you ARE using flow. Not a solution I expected to my problem 😄
