### ISSUE TITLE
Support type spread in flow-types

### ISSUE THREAD

**Issue by danez** [babel/babylon#416]
### Input Code

```js
type A = {...TypeA, ...TypeB}
```

### Expected Behavior
Should parse

### Current Behavior
Throws

https://github.com/babel/babel-eslint/issues/443
https://github.com/facebook/flow/commit/ad443dc92879ae21705d4c61b942ba2f8ad61e4d

//cc @samwgoldman

**Comment by conartist6** [comment]
I am building a PR for this.
