### ISSUE TITLE
Babylon translates xhtml character entities to UTF-8 inside JSX tags

### ISSUE THREAD

**Issue by ChristianHersevoort** [babel/babylon#423]
This not a bug per se, but I was wondering why babylon translates HTML-entities inside a JSX-tag into UTF-8 characters. (Source: https://github.com/babel/babylon/blob/7.0/src/plugins/jsx/index.js#L144). I can't find anything about this in the JSX spec.

I encountered this "feature" while running prettier, it removes xhtml character entity information from the AST, and thereby causing "wrong" formatting. 

I fixed this "bug" [here](https://github.com/ChristianHersevoort/babylon/commit/d0c204c17e8f5d983c7c5b5bd0a445c63e5c173), I can also make a PR but I don't know the impact of this change. 

### Expected Behavior
Keep HTML-entities data in the AST 

### Current Behavior
Babylon translates specific HTML-entites to UTF-8 characters. Babylon doens't have this behavior for "normal" code. 

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0-branch (#0545173)
| node             | 7.6.0
| npm              | 4.3.0
| Operating System | Arch Linux

**Comment by hzoo** [comment]
Hey @ChristianHersevoort! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by danez** [comment]
The problem is probably that we do not have raw values for this Strings which is going to be fixed in #344.

Why we actually convert html entities is most probably as if jsx gets translated to `React.createElement()` it needs to be UTF-8. Not 100% sure about this though.

**Comment by ChristianHersevoort** [comment]
Closing my issue in favor of #344

**Comment by dlutwuwei** [comment]
Did this problem resolved in the 7.0.0 beta version?
