### ISSUE TITLE
[7.0] Consider making AssignmentProperty have that type in the ast

### ISSUE THREAD

**Issue by Jamesernator** [babel/babylon#434]
In the spec and resulting AST we have that `AssignmentProperty` does not gain type `AssignmentProperty` e.g. this:

```js
const {z: y} = foo
```

Parses to
```js
...
type: 'ObjectPattern',
properties: [{
    type: 'ObjectProperty', // This is what I propose changing
    ...
}]
...
```

Whereas I'd propose making it parse to:

```js
...
type: 'AssignmentProperty',
properties: [{
    type: 'AssignmentPattern',
    ...
}]
...
```

As it stands this is the only Node that has a type field different to its definition, changing it would help traversing ObjectPatterns in a way that doesn't require knowledge about the parent (or further ancestor when nested).

**Comment by hzoo** [comment]
Hey @Jamesernator! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by danez** [comment]
If you use babylon standalone, consider enabling the estree plugin, which will output estree compatible AST.

`ObjectProperty` is a custom node that is used in babel. Before we consider renaming this node, we eventually should think about switching back to estree then by default for this case.

**Comment by hzoo** [comment]
Not going to be changing anything in the AST but we could talk about doing some changes in bulk (or switching to shift, etc) but would cause for a lot of pain in the plugins/etc

**Comment by bakkot** [comment]
This particular case is one that Shift handles [particularly well](http://shift-ast.org/parser.html?type=Script&code=const%20%7Bz%3A%20y%7D%20%3D%20foo%3B%0A(%7Bz%3A%20y%7D%20%3D%20foo)), incidentally :).

(The distinction Shift makes between assignment and binding is relevant because `({a: b.c} = 0)` is legal but `const {a: b.c} = 0` is not, and it's nice to have the type system enforce that.)
