### ISSUE TITLE
export type from "module" is a SyntaxError

### ISSUE THREAD

**Issue by Jamesernator** [babel/babylon#437]
### Input Code
Basically this is a SyntaxError:
```js
export type from "./some-module.js"
```

[example](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=true&presets=stage-1&targets=&browsers=&builtIns=false&code=%0Aexport%20type%20from%20%22.%2Ffoo.js%22&experimental=true&loose=false&spec=false&playground=true&stage=0)

### Babylon/Babel Configuration
Using Babylon plugin: ['exportExtensions'] but it affects Babel too using the babel plugin 'transform-export-extensions'.

### Current Behavior
Currently this results in a SyntaxError, I'm fairly certain it's because of flow parsing which uses `export type ...`.

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.16.1
| node             | v7.7.3
| npm              | 4.1.2
| Operating System | Ubuntu

**Comment by hzoo** [comment]
Hey @Jamesernator! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
