### ISSUE TITLE
Parse error on Flow type wildcard

### ISSUE THREAD

**Issue by danez** [babel/babylon#44]
```
let f: * = (x: null | *): (*) => {}
```

> Looks like the parser doesn't expect * outside of type argument brackets. Here are some examples.

copied from https://phabricator.babeljs.io/T7060

Can someone confirm that this is valid flow syntax? @gabelevi maybe

Because it seems to work when doing:
```
let f: * = (x: null | *): * => {}
```

**Comment by kittens** [comment]
Looks like Flow parses this so it's valid.

**Comment by kittens** [comment]
Removed a restriction that was inherited from `esprima-fb` that doesn't seem to be valid anymore. @jeffmo can you confirm?

**Comment by jeffmo** [comment]
This is valid syntax, yea.

`*`, in Flow, means "infer this type" (AKA: Insert an OpenT here)
