### ISSUE TITLE
Discussion: Should we have sourceType: "auto"

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babylon#440]
In Babel 6, we've hardcoded everything to be `sourceType: "module"` by default, which has been a bit of a problem because people often run Babel on arbitrary code that they don't own, and sometimes that code is written assuming it will be treated as a script. This leads to complaints about `this` being replaced at the top level, among other things.

Would people be open to adding an `auto` sourceType option that would use the unambiguous grammar proposal? https://github.com/bmeck/UnambiguousJavaScriptGrammar

The longterm effect I'd expect from this for users is that users who have normal CommonJS modules won't automatically get `use strict` at the top of their files anymore, unless they opt into that plugin, which I think it a very reasonable thing to do.

The other side of it is that I want to start locking down the behavior of modules specifically, so usage of `module.exports` or `require` alongside `import` would be an error, which I believe is also the case in Webpack now? We'll want a flag so people can opt out of the behavior when switching from Babel 6 to 7, though.

**Comment by Jamesernator** [comment]
Yes that'd be awesome.

**Comment by danez** [comment]
In webpack you can use require alongside with import, which I think is a common pattern if you want to lazy-require stuff or but requires in `if (NODE_ENV==='development' )` so the whole require+the required dependencies get stripped on production. import() is not an alternative as webpack treats import() as splitpoint by default, though this can be turned of by changing the parser configuration in webpack.

**Comment by loganfsmyth** [comment]
@danez Assuming I'm understanding the planned behavior in Node right, `require` and the others like `module.exports` and such will not exist inside an ES module. That means if you want to use `require` you'd have to be write a CommonJS module, and then import that from your ES6 module.

I'm still on the fence about adding that restriction to Babel as default in 7.x, may just be an opt-in flag. Webpack 2 does not implement the restriction of using `require`, but they _do_ disallow using `exports` alongside ES6 module syntax, so that we should probably do at least.

Either way I do think it's beneficial for Babel to default to "auto", because it means that people don't need to explicitly set `sourceType`. Most people don't know about it, and Babel doesn't currently expose a way to toggle it based on extension or something, so you can't mix and match in a codebase. With `auto`, if you run Babel on a file without `import` or `export`, we can stop automatically adding `use strict` and we won't automatically add `.__esModule` and we won't replace `this` with `undefined`, which are all problems people tend to hit unexpectedly because most people don't know about the grammar split.

**Comment by jdalton** [comment]
In time for Lodash v5 I'll be introducing an ESM loader for broad adoption.
It won't restrict `require` use either.

**Comment by jdalton** [comment]
The kind of "auto" detection is how we'll be handling things too.

**Comment by ljharb** [comment]
I'm fine with the concept of "auto", but I would strongly discourage using the unambiguous grammar proposal (in any tool or library) until it's made progress in TC39. At this stage, it seems to have very strong opponents, so it's likely it will never reach stage 4. (it never reached consensus for any stage; [TC39 meeting notes](https://github.com/rwaldron/tc39-notes/blob/3eb7d06f12559c95bf674f75d955d2bd14380b28/es7/2017-01/jan-25.md#13iia-proposed-grammar-change-to-es-modules))

You absolutely can infer the Module parsing goal if `import` or `export` appears - however, the lack of either of those keywords absolutely can not be used to distinguish between Script and Module. It is simply *wrong* to decide something is a Script simply because it lacks `import` or `export`.

Separately, I'm not aware of any plan to make `require` unavailable in ES Modules in `node` - @bmeck can confirm.

**Comment by Kovensky** [comment]
AFAIK from the previous drafts, `module`, `exports`, `__dirname`, `__filename` et al will be gone in modules. However, `global` and `require` stay.

**Comment by jdalton** [comment]
> You absolutely can infer the Module parsing goal if import or export appears - however, the lack of either of those keywords absolutely can not be used to distinguish between Script and Module.

The  `import/export` detect seems like a pretty good default to me.
Folks can always be explicit about their `sourceType`. 

> , but I would strongly discourage using the unambiguous grammar proposal (in any tool or library) until it's made progress in TC39. 

Naw this kind of "auto" detect doesn't need TC39's blessing or Nodes and is already in use by other tools (like TypeScript). It's super simple stuff.

**Comment by ljharb** [comment]
It's not simple in that there exist valid files that can be both a Script or a Module (they neither import nor export anything), and they can do different things based on the parsing goal.

It's not about "blessings" - this isn't about "permission" - it's that it will result in broken code in nonzero cases, so it's wrong to do it - no matter which tools are doing it already.

**Comment by jdalton** [comment]
> It's not simple in that there exist valid files that can be both a Script or a Module (they neither import nor export anything), and they can do different things based on the parsing goal.

That's when folks for those cases can be explicit about their `sourceType` in their babel config.

**Comment by ljharb** [comment]
Yes, that's one solution - one they will have to know about, know how to apply, and figure out that their code is broken in a very subtle way such that it can trigger this process.

Defaults should be safe. Defaulting to breaking nonzero people is not safe, no matter how convenient it might make things for other groups of people.

**Comment by jdalton** [comment]
I think defaults should appeal to the common cases. And while folks can have side-effect only modules they're not the common case. This feels like getting hung-up on an edge case more than anything else. They could always float things in an RC to see how things go.

**Comment by jdalton** [comment]
If things don't work out "auto" could always be an-option just not the default.

**Comment by ljharb** [comment]
I'm not sure I understand why it'd be better to silently do the wrong thing - ever - rather than forcing the user to make an explicit choice.

**Comment by jdalton** [comment]
> I'm not sure I understand why it'd be better to silently do the wrong thing

It's outlined in the issue summary at the top.
I donno. I think we disagree about much of this kind of stuff 😸

**Comment by ljharb** [comment]
The issue summary at the top outlines the hazards of silently assuming the wrong thing - which supports my position.

**Comment by jdalton** [comment]
> The issue summary at the top outlines the hazards of silently assuming the wrong thing - which supports my position.

Naw, the issue is folks run it on code that can be a mix of source types so one source type doesn't fit all which is where an "auto" option comes in handy.

**Comment by ljharb** [comment]
Babel running on "arbitrary code that they don't own" and guessing the parsing goal, when it's impossible to know for sure if it's a Script or a Module, is hazardous - whether it's "module", "script", or "auto".

I like the unambiguous parsing proposal; I wanted to see it land - but since it isn't likely to, I think it's hugely dangerous for anything to rely on it. Things will break.

**Comment by jdalton** [comment]
> when it's impossible to know for sure if it's a Script or a Module, is hazardous - whether it's "module", "script", or "auto".

I think it's possible to have a pretty good hunch. Auto doesn't necessarily mean ironclad though if there was such a thing that option, "ironclad" would be rad.

**Comment by ljharb** [comment]
If there was a way to determine whether a file (that isn't already "definitely a Module") would behave the same in both strict or sloppy mode, and also whether its behavior depended on running in the global scope directly or not, then perhaps you'd be able to safely "ironclad" make a choice for that file - but at that point, it wouldn't matter which you chose.

**Comment by jdalton** [comment]
Pinging back from our offline thread Babel could warn if it encounters ambiguous code so folks could investigate and adjust/ignore as needed.

**Comment by loganfsmyth** [comment]
I think having it opens up options for people, but I agree that I care less what the default is. I think in a perfect world `script` would be the default for `.js` with `sourceType` in Babel's config making it configurable and `.mjs` would be `module` without it being configurable.

My motivation for proposing it as a default is that Babel's current `module` default isn't ideal and forcing it to `script` in 7.0 feels like a pain for most users.

That said, defaulting to `script` with `auto` being exposed as an option might not be the end of the world?

**Comment by bmeck** [comment]
If things are ever completely disambiguated by spec I'd be happy with `auto` being the default, but thats possibility is not looking likely in near future.

**Comment by jdalton** [comment]
> That said, defaulting to script with auto being exposed as an option might not be the end of the world?

You could keep the default as it is, "module", and have the "auto" option.

**Comment by bmeck** [comment]
@jdalton right now it doesn't do the checking based upon file extension like stated above. The Node proposal continues to use `.mjs` as the only way to generate an ESM by default. I think `.js` is more likely to be a Script than a Module if a `.js` is encountered after that ships.

**Comment by jdalton** [comment]
I understand that. I'm saying as things are it would be nice to continue to keep the target as "module". I'd prefer it not to start the js/mjs split as the default in v7. That could be always be an option as "auto" is an option.

**Comment by bmeck** [comment]
For v7, I'm pretty neutral; but after ESM ships in Node I am heavily against defaulting to "module".

**Comment by jdalton** [comment]
> For v7, I'm pretty neutral; but after ESM ships in Node I am heavily against defaulting to "module".

That makes sense.

**Comment by ljharb** [comment]
To be clear; my primary argument is about safety, which only applies to what the default is. Separately, I don't think using the "unambiguous" proposal is ever a good idea, but I'm not a blocker on that, proverbial or otherwise.

Once node ships modules, I think every tool in the ecosystem both must, and will inevitably anyways, conform to the detection semantics node ships; and that's what I'd want to see Babel adopt as the default.

**Comment by danez** [comment]
A little off topic and probably a stupid question but why is it so important to differ between ESmodules and commonjs? Couldn't node simple add support for the import/export syntax and do the same as with require?
```
import x from 'x'; --> const x = require('x').default;
export default ... --> exports.default = ...
```
This is not be spec conform but ¯\_(ツ)_/¯. IMHO most of the users will not care for all the special cases that the spec defines, like if an import of modules is validated before code execution or dynamically. And a lot of projects already use exactly this pattern with babel.

I'm missing a lot of background on this topic, but as a js developer the new .mjs file extension sounds weird.

**Comment by jdalton** [comment]
@danez To avoid derailing the [babel slack](https://slack.babeljs.io/) is perfect for side conversation.
