### ISSUE TITLE
Babylon doesn't parse for of regex

### ISSUE THREAD

**Issue by vjeux** [babel/babylon#456]
```js
for (a of /a/) {}
```

```js
SyntaxError: Unexpected token (1:10)
> 1 | for (a of /a/) {}
    |           ^
```

But it seems to parse both on flow and Chrome:

![image](https://cloud.githubusercontent.com/assets/197597/24816731/ab34fb0a-1b8e-11e7-9bd4-124902dccf45.png)

**Comment by hzoo** [comment]
Hey @vjeux! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
