### ISSUE TITLE
Babylon doesn't parse function argument with class and comparison

### ISSUE THREAD

**Issue by vjeux** [babel/babylon#457]
```js
function x(y = class {} < 1) {}
```

```js
SyntaxError: Unexpected token, expected , (1:24)
> 1 | function x(y = class {} < 1) {}
    |                         ^
  2 | 
```

This parses just fine in Flow and Chrome

![image](https://cloud.githubusercontent.com/assets/197597/24816875/5f46fca6-1b8f-11e7-8a8d-d65a896df89e.png)

**Comment by hzoo** [comment]
Hey @vjeux! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by loganfsmyth** [comment]
Dang, nice edge case there haha.

**Comment by vjeux** [comment]
This was found with @lydell fuzzer applied on prettier if you are curious :)

**Comment by nicolo-ribaudo** [comment]
Now it seems to work both in babylon@7.0.0-beta.16 and babylon@6.17.4

https://runkit.com/embed/dlq8yt28haf8

**Comment by hzoo** [comment]
Ok cool, thanks for checking @nicolo-ribaudo
