### ISSUE TITLE
Faster without tokens array

### ISSUE THREAD

**Issue by andy-ms** [babel/babylon#458]
Comment out these lines in `tokenizer/index.js`:
	* `this.state.tokens.push(new Token(this.state));`
	* `this.state.tokens.push(comment);`

This brought the time in my perf script (https://gist.github.com/andy-ms/138e270e510620945df1499181c05892) down from ~7.9 seconds to ~5.7 seconds.

The `tokens` array is attached to the file object in `parseTopLevel`, but this doesn't seem to be documented. Can it be removed or made optional?

**Comment by hzoo** [comment]
Hey @andy-ms! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by hzoo** [comment]
Yeah I guess we can add a `tokens` option since doesn't look like other parsers even have this in the AST

**Comment by forivall** [comment]
acorn has an `onToken` option, to which can you can pass a function to build the tokens array. I'd consider going back to that behaviour.

**Comment by hzoo** [comment]
Yeah I don't remember when/why we removed it earlier

**Comment by xtuc** [comment]
Good idea :+1: 

Removing the token array would be a breaking change for tools built on top of Babel (at least I guess so). I'm fine with the performance boost but we need a option in case the user wants them.
