### ISSUE TITLE
Allow custom plugins

### ISSUE THREAD

**Issue by yuri-karadzhov** [babel/babylon#466]
In order to test babel plugins it would be really nice to have ability to pass plugin instance to babylon. The test could look like this

```js
import {expect} from 'chai';

import * as babylon from 'babylon';
import generate from 'babel-generator';
import myAwesomePlugin from './my-awesome-plugin';

describe('myAwesomePlugin', () => {
  it('transform code with myAwesomePlugin', () => {
    const code = 'code to transform';
    const ast = babylon.parse(code, {
      plugins: [myAwesomePlugin]
    });
    const transformed = generate(ast, {}, code);

    expect(transformed.code).to.equal('expected transformed result');
  });
});
```

**Comment by hzoo** [comment]
Hey @yuri-karadzhov! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by hzoo** [comment]
Sorry we don't have plans for custom plugins outside of babylon atm, we will accept PRs for https://github.com/tc39/ecma262#current-proposals though. Ref https://github.com/babel/babel/issues/1351
