### ISSUE TITLE
Parses invalid number literal

### ISSUE THREAD

**Issue by jj-choi** [babel/babylon#467]
### Input Code

```js
var a = 0123.;
```

### Babylon/Babel Configuration

default

### Expected Behavior

Parser should throw a syntax error.

### Current Behavior

```
NumericLiteral(123.0)
```

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.16.1
| node             | 6.10.2
| npm              | 3.10.10

**Comment by hzoo** [comment]
Hey @jj-choi! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by alxpy** [comment]
yes, it looks like a bug. I will work on this.
