### ISSUE TITLE
Location ObjectTypeAnnotation flow types shouldn't include the comma

### ISSUE THREAD

**Issue by vjeux** [babel/babylon#470]
The location reported by babylon is incorrect. We're using this location for `// prettier-ignore`. See https://github.com/prettier/prettier/issues/1248.

### Input Code

```js
type x = {
  foo: number,
  bar: number
};

var x = {
  foo: number,
  bar: number  
};
```

Reproduces for both 7.0.0-beta.8 and babylon6-6.16.1
![image](https://cloud.githubusercontent.com/assets/197597/25026624/1f45a0cc-205c-11e7-9e59-41bd9a69a7bd.png)

The equivalent for normal objects doesn't report the comma, nor the flow parser.

![image](https://cloud.githubusercontent.com/assets/197597/25026647/3ff1862e-205c-11e7-8f17-659088ba0506.png)

http://astexplorer.net/#/gist/8828872e0b490bd921911433b02c161d/efb48240ee818f4d9af2033bf38d3f0a319ad4db

Thanks :)

**Comment by hzoo** [comment]
Hey @vjeux! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by vjeux** [comment]
Yay, thanks!
