### ISSUE TITLE
Parsing error of generic function when enabling jsx and flow plugins

### ISSUE THREAD

**Issue by tibdex** [babel/babylon#471]
I found this while using `prettier` 1.1.0.

### Input Code

```js
const identity = <T>(t: T): T => t;
const a = 1;
```

### Babylon/Babel Configuration

```js
{
  plugins: ['jsx', 'flow']
}
```

### Expected Behavior

The code is valid and `babylon` should be able to parse it.

### Current Behavior

`babylon` throws `Unexpected token (2:0)`. You can see it live on the [prettier playground](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20identity%20%3D%20%3CT%3E(t%3A%20T)%3A%20T%20%3D%3E%20t%3B%5Cnconst%20a%20%3D%201%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D).

Removing the `jsx` plugin and only enabling the `flow` one makes `babylon` able to parse the code correctly. 

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.8
| node             | 6.9.1
| yarn              | 0.22.0
| Operating System | Windows 10

**Comment by hzoo** [comment]
Hey @tibdex! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by tibdex** [comment]
Thanks @hzoo, of course no hurry :) ! I just thought that since the issue is impacting the latest release of `prettier` lot of people were going to stumble into it. So I just went ahead and created a ticket here and on the `prettier` repo so that people also experiencing it can see that there is already an issue for it.

**Comment by tibdex** [comment]
FYI I used *git bisect* and the issue appeared in https://github.com/babel/babylon/commit/32eabf620b9d5eaf190969cc4a38f7775626a3f.

Putting the code back as it was before https://github.com/babel/babylon/pull/405 fixes the parsing error but seems to put back the code in a incorrect state if https://github.com/babel/babylon/issues/404 is legit. Indeed, I added `console.log` statements before `this.state.context.push(ct.parenExpression);` and `this.state.context.pop();` and here is the sequence:

```
push // 1
push // 2
pop // 1
push // 2
pop // 1
push // 2
pop // 1, missing a "pop" if the counter is expected to go back to 0, but is it ? ...
```
