### ISSUE TITLE
Fails to parse Flow-annotated polymorphic methods which name is a keyword

### ISSUE THREAD

**Issue by danez** [babel/babylon#48]
> I started using Flow recently, and was delighted to see that Babel (which I was already using) supported stripping Flow types by default already! I just found a funny issue though:
>
> sebmck: It's being parsed as a JSX tag for some reason.
> sebmck: Figured it out exprAllowed is being set to true on delete tokens so the < is being interpreted as the start of a JSX starting tag expression.
> thejameskyle: @sebmck is this an easy one to tackle?

```
class Foo {
  delete<T>(item: T): T {
    return item;
  }
}
```

copied from https://phabricator.babeljs.io/T1737

**Comment by danez** [comment]
I tried to solve this some months ago, but couldn't figure out how to fix. This not only happens for `delete` but also fro some other keywords, couldn't remember which. Maybe `void`.

**Comment by danez** [comment]
```
declare class A {

while<T>(): void; // this parses
do<T>(): void; // this does not
}
```

> The input code should parse, however it errors at the '<' after the 'do'.
>
> The above fails to parse because the 'do' keyword is marked as {beforeExpr: true} in tokenizer/types.js.
> Then tokenizer interprets the '<' after the do as the start of a jsx tag, rather than as a relational '<'.
> 
> The 'while' variant works because it is not marked beforeExpr.
>
> The above will repro with any method whose name is a keyword marked with beforeExpr true, which are:
> case, default, do, else, return, throw, new, extends, yield, in, instanceof, typeof, void, delete.

https://phabricator.babeljs.io/T7284

**Comment by vkurchatkin** [comment]
The same for get/set

**Comment by vkurchatkin** [comment]
Fixed the get/set part: https://github.com/babel/babylon/pull/55

**Comment by vkurchatkin** [comment]
@danez it seems that your examples work on master

**Comment by danez** [comment]
No both are not working yet.

**Comment by vkurchatkin** [comment]
Hmm, they work for me. Do you have jsx plugin enabled?

**Comment by danez** [comment]
yes
```
declare class A {
   while<T>(): void; // this parses
   do<T>(): void; // this does not
}
```

```
{
  "sourceType": "module",
  "plugins": ["jsx", "flow", "asyncFunctions"]
}
```

```
Unexpected token (3:2)
```

**Comment by danharper** [comment]
I've got a WIP of a fix for this. I think there's still some edge cases to cover to match Flow though (or, they might be bugs in Flow..) I'll probably have a PR ready this weekend.
