### ISSUE TITLE
babylon v6.17.0; no git-tag, no changelog on github repo

### ISSUE THREAD

**Issue by SerkanSipahi** [babel/babylon#483]
Is there any reason that babylon v6.17.0 which is already deployed on npm has no git-tag (repo) and no changelog (repo)?!?

**Comment by hzoo** [comment]
Hey @SerkanSipahi! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by xtuc** [comment]
Yes good catch, that correct. I'll ask the Babylon folks for a new release.

**Comment by xtuc** [comment]
The changelog was added and no new commit were added to the branch. I did a git-tag https://github.com/babel/babylon/releases/tag/v6.17.0

**Comment by SerkanSipahi** [comment]
@xtuc thanx
