### ISSUE TITLE
Duplicated nodes in object destructuring node

### ISSUE THREAD

**Issue by markelog** [babel/babylon#49]
Consider this example - 

``` js
({ test = 1 } = {})
```

Then relevant parts of generated AST would look like this - 

``` js
"properties": [
  {
    "type": "ObjectProperty",
    "start": 3,
    "end": 11,
    "loc": {
      "start": {
        "line": 1,
        "column": 3
      },
      "end": {
        "line": 1,
        "column": 11
      }
    },
    "method": false,
    "shorthand": true,
    "computed": false,
    "key": {
      "type": "Identifier",
      "start": 3,
      "end": 7,
      "loc": {
        "start": {
          "line": 1,
          "column": 3
        },
        "end": {
          "line": 1,
          "column": 7
        }
      },
      "name": "test"
    },
    "value": {
      "type": "AssignmentPattern",
      "start": 3,
      "end": 11,
      "loc": {
        "start": {
          "line": 1,
          "column": 3
        },
        "end": {
          "line": 1,
          "column": 11
        }
      },
      "left": {
        "type": "Identifier",
        "start": 3,
        "end": 7,
        "loc": {
          "start": {
            "line": 1,
            "column": 3
          },
          "end": {
            "line": 1,
            "column": 7
          }
        },
        "name": "test"
      }
```

Notice duplication in `ObjectProperty` for `key` and in `AssignmentPattern` for `left` properties - `Identifier` node is used twice.

This creates weird issues for traversing and for code generation.

**Comment by kittens** [comment]
This is intentional. What behaviour are you proposing?

**Comment by mdevils** [comment]
The one which does not repeat `Identifier` twice and does not require changing it in two places when modifying AST I guess :)

**Comment by kittens** [comment]
That's not very helpful, what node structure are you proposing?

**Comment by mdevils** [comment]
First thing comes to my mind.

```
ObjectPattern {
  properties: [ AssignmentPatternProperty | Property ]
}

PropertyAssignmentPattern <: Node {
  key: Identifier
  pattern: Pattern
}
```

**Comment by mdevils** [comment]
To be even more precise, `Property` does not really match `ObjectPattern` well since it had a lot of fields that are not relevant to `ObjectPattern`. I predict `ObjectPatternProperty` in some bright future.

**Comment by kittens** [comment]
It's going to be a breaking change, while we do have that luxury since we forked the AST from ESTree it's still tricky because we have existing transforms and Babel rarely has a major.

The existing node definition is good for transformations as it doesn't require every single transform that targets object patterns to know how and when to perform explosion of shorthands. The idea of making shorthands distinct is obviously appealing to the idea of a CST but I'm unconvinced that it's an appropriate modification to an AST that's (currently) targeted so generally at transforms.

I understand it's annoying but IMO the pros far outweigh the cons as it leads to more reliable and solid transforms. I'm not convinced that the extra code needed to handle it is burdensome, for reference [here](https://github.com/babel/babel/blob/4e1b4aecfdafe491baeab4271f131f721692017a/packages/babel-generator/src/generators/types.js#L64-L67) is the code in `babel-generator` that handles it.

**Comment by kittens** [comment]
@markelog Can you elaborate on the complexity around traversal that you mentioned in your original post?

**Comment by markelog** [comment]
You will get two `Identifiers` when it seems there should be only one and also see https://github.com/cst/cst/blob/996ce8451d1bdf14e06439533499d2e320cb3342/src/elementTree.js#L105-L119

**Comment by markelog** [comment]
And there is an example of code generation issue - https://github.com/cst/cst/issues/127, since there is two identifiers they are duplicated

**Comment by kittens** [comment]
That bug just seems to be consequent of the fact that it uses the AST in conjunction with tokens rather than relying entirely on the AST.

**Comment by markelog** [comment]
> Those issues just seem to be consequent of the fact that it uses the AST in conjunction with tokens rather than relying entirely on the AST.

Yes, that's part of the issue, same kind thing could be viewed with any traversal though, like:

```js
let i = 0;

let ast = require("babylon").parse("({ test = 1 } = {})", {});

let result = require('estraverse').traverse( ast.program, {
    keys: require("babel-types").VISITOR_KEYS,
    enter: function (node) {
    	if (node.type === 'Identifier') {
        	i++;
        }
    }
});

console.log(i); // 2
```

I understand you don't want to change that because you don't need this and we are only one consumer of this AST who is mentioned it, so there is could be any justification for denial really :).

**Comment by markelog** [comment]
>  so there is could be any justification for denial really :).

By that, i mean if you don't want to change then no big deal, we would be just force to add couple hacks, in any case it seems you make your mind already

**Comment by hzoo** [comment]
Since it looks like we need an AST change that we'd not like to do with other changes in bulk, closing
