### ISSUE TITLE
export default function has null id, but spec says id must not be null

### ISSUE THREAD

**Issue by andy-ms** [babel/babylon#502]
### Input Code

```js
export default function() {}
```

### Babylon Use

```js
const babylon = require("babylon");
const src = "export default function() {}";
const ast = babylon.parse(src, { sourceType: "module" });
console.log(JSON.stringify(ast.program.body[0], undefined, 2));
```

### Expected Behavior

Either:
* This should be parsed as a FunctionExpression.
* FunctionDeclaration may have a null id.

### Current Behavior

[Spec](https://github.com/babel/babylon/blob/e81b5f8af273e92667696c51a870c64c4a163b18/ast/spec.md#functiondeclaration) declares that FunctionDeclaration must not have a null id. 

But in the output:
```json
"declaration": {
  "type": "FunctionDeclaration",
  ...
  "id": null,
  ...
}
```

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.8
| node             | 7.9.0
| npm              | 4.2.0
| Operating System | Linux Mint 18

Related: #257

**Comment by hzoo** [comment]
Hey @andy-ms! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by loganfsmyth** [comment]
Definitely a spec bug. FunctionDeclarations are allowed to not have an ID, but only when nested in an `ExportDefaultDeclaration`.

**Comment by loganfsmyth** [comment]
Parsing as a FunctionExpression would change the hoisting behavior and potentially break circular dependencies.

**Comment by hzoo** [comment]
I believe I just didn't change the spec in babylon or estree either. https://github.com/estree/estree/issues/98#issuecomment-278997010

**Comment by hzoo** [comment]
https://github.com/babel/babylon/pull/503
