### ISSUE TITLE
Miscellaneous undocumented properties

### ISSUE THREAD

**Issue by andy-ms** [babel/babylon#505]
I ran into these extra properties while trying to validate parsed ASTs using `babel-types`, which lacks validators for them. They are not in the spec either.

| Code | Description |
| ---- | ------- |
| `(() => 0);` | `ArrowFunctionExpression` has undocumented `"generator": false`. |
| `function f() {}`, `(function() {})`, `({ m() {} })`, `class C { m() {} }` | All (`FunctionDeclaration`, `FunctionExpression`, `ObjectMethod`, `ClassMethod`) have undocumented `"expression": false`. |
| `({ p: 0, m() {} });` | Both (`ObjectProperty`, `ObjectMethod`) have undocumented `method` boolean. Seems redundant given that they have different `type`s.
| `try {} catch (e) {}` | `TryStatement` has undocumented `"guardedHandlers": []`. |

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.8
| node             | 7.9.0
| npm              | 4.2.0
| Operating System | Linux Mint 18

**Comment by hzoo** [comment]
Hey @andy-ms! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
