### ISSUE TITLE
Syntax error for overwriting constructor type in flow class

### ISSUE THREAD

**Issue by philipp-spiess** [babel/babylon#508]
In a recent version change, parsing flow files introduced an error when a flow class overwrites the constructor type.

### Input Code

```js
class Foo {
  constructor: () => this;
}
```

### Babylon/Babel Configuration

```js
{
  "plugins": [
     "transform-class-properties",
      "transform-object-rest-spread"
   ],
   "presets": ["latest", "react"]
}
```

### Expected Behavior

The file parses correctly. Flow parser accepts the syntax properly

### Current Behavior

```
error  Parsing error: Classes may not have a non-static field named 'constructor'
```

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          | 6.17.0 (worked in 6.16.1)
| node             | v6.9.1
| npm              | 3.10.8 
| Operating System | macOS

**Comment by hzoo** [comment]
Hey @philipp-spiess! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by bakkot** [comment]
Ah, that was me at #351, sorry.

What does this syntax do? Why does flow accept it? Do they accept it on purpose? (Also, why doesn't flow have formal documentation of their syntax?)

**Comment by philipp-spiess** [comment]
We used it to fix a missing type for a constructor from a class that we extend (`Immutable.Record` to be more specific). It's kinda hacky since it uses the [class fields API](https://flow.org/en/docs/types/classes/#toc-class-fields-properties) and defines constructor as a property.

[Here's](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAMTjjAG9UwwM4A7XAFwCcBXDBuJgCihIC4wtFgFsARgFMmASnKUq1OrjgxxAOngBzHiSkBuOQF9URzDnxgAQtiZhxADwbjaAEwJdicAdloBPGRSoaemY2DiYBbU8wRiYAS1oNGQBeAD5La30jKlRacSQrbgBGACYAZgAWKSA) a working example in flow that uses this technique.

> Also, why doesn't flow have formal documentation of their syntax?

I can't help you there :)
