### ISSUE TITLE
Object destructuring inside the rest parameter

### ISSUE THREAD

**Issue by peey** [babel/babylon#512]
Babel is unable to parse `({ x, ...{ y, z } } = o)`. It's valid according to the [spec](https://github.com/tc39/proposal-object-rest-spread/blob/master/Rest.md).

### Input Code / Babylon Configuration

```js
babylon.parseExpression("{ x, ...{y, z} } = o", {"plugins":["objectRestSpread"]});
```
### Expected Behavior
It should parse correctly to be transformed into a functionally equivalent code of the following: 

```js
x = o.x
rest = _objectWithoutProperties(o, ["x"])
y = rest.y
z = rest.z
```

### Current Behavior

This error is thrown

```
SyntaxError: Invalid left-hand side in rest property (1:8)`
```

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  code on master (#0e12f56)
| node             | 6.10.3
| npm              | 3.10.10
| Operating System | Ubuntu 16.04

**Comment by hzoo** [comment]
Hey @peey! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
