### ISSUE TITLE
[7.0][question] Node.js requirement: => 4.2.0

### ISSUE THREAD

**Issue by futagoza** [babel/babylon#513]
## Problem

I just upgraded my [babel preset](https://www.npmjs.com/package/babel-preset-futagozaryuu) to use the Babel 7 alpha/beta packages, but after adding the preset to [a specific project](https://github.com/futagoza/epeg.js) and then committing the change to GitHub, it automatically ran the Travis build (as expected), but during the install process on [Build 36.1: Node.js 4](https://travis-ci.org/futagoza/ePEG.js/jobs/230106858#L150), NPM gave a warning about Babylon requiring Node.js 4.2 or higher, but after my next commit, there was no warning from NPM on [Build 37.1: Node.js 4](https://travis-ci.org/futagoza/ePEG.js/jobs/230129953#L150).

Curious about this, I went through the history for [babylon/package.json](https://github.com/babel/babylon/commits/master/package.json), and found that the last time babylon didn't require `node >= 4.2` was on commit https://github.com/babel/babylon/commit/b6b4610cea6fea4fb09ea349341b54f72145a334, but right after that (on the same day, 27/01/2017) there was a [merge commit](https://github.com/babel/babylon/commit/0309a5ba8a1552c13ecb144676973e9965a33ba5) that set `node >= 4.2`.

Problem is that this commit doesn't show it in the diff, instead clicking on `View` will show the undocumented addition of `"engines": { "node": ">=4.2.0" }`, which seems rather odd.

I wouldn't usually care about this, but before increasing the minimum Node.js version for my project and/or preset, I'd like to know why.

## Question

1. If this was intentional, why set the minimum to 4.2?
2. Why wasn't this documented in the commits?

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          | 7.0.0-beta.8
| node             | 7.10.0
| npm              | 4.2.0
| Operating System | Windows 10 Home x64

**Comment by hzoo** [comment]
Hey @futagoza! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by danez** [comment]
The reason that we choose 4.2 is because the node LTS started with 4.2. 

But as our code will also work with 4.0 we can also change it to `>= 4`

**Comment by hzoo** [comment]
We want the minimum to be LTS yep!
