### ISSUE TITLE
ClassMethod key is not an Expression

### ISSUE THREAD

**Issue by EmpireWorld** [babel/babylon#514]
I have seen you have used **Expression** type in **ClassMethod key** property while it should be **Identifier**:

```js
interface ClassMethod <: Function {
  type: "ClassMethod";
  key: Expression; // This should be Identifier
  kind: "constructor" | "method" | "get" | "set";
  computed: boolean;
  static: boolean;
  decorators: [ Decorator ];
}
```

[**View source version**](https://github.com/babel/babylon/blob/master/ast/spec.md#classmethod)

Here is the expected interface:

```js
interface ClassMethod <: Function {
  type: "ClassMethod";
  key: Identifier; // Now fixed
  kind: "constructor" | "method" | "get" | "set";
  computed: boolean;
  static: boolean;
  decorators: [ Decorator ];
}
```

Here is file url: https://github.com/babel/babylon/blob/master/ast/spec.md

Thanks.

**Comment by hzoo** [comment]
Hey @EmpireWorld! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by bakkot** [comment]
@EmpireWorld, it can't just be an Identifier because computed property keys allow arbitrary expressions:

```js
class A {
  [an.arbitrary(expression)] () {}
}
```

Note that Literal is a subtype of Expression, so for non-computed names you can still have a Literal in that position.

So, no, it's correct as is.

**Comment by EmpireWorld** [comment]
@bakkot We can use `Expression | Identifier` instead of `Expression` because when i try the below:

```javascript
class ExampleClass () {

    sampleMethod () {
        
    }

}
```
I was get the below result as key:
```
Node {
  type: 'Identifier',
  start: 2595,
  end: 2607,
  loc: 
   SourceLocation {
     start: Position { line: 3, column: 4 },
     end: Position { line: 3, column: 11 },
     identifierName: 'exampleMethod' },
  name: 'exampleMethod' }
```

**Comment by maurobringolf** [comment]
Aren't `Expression|Identifier` and `Expression` equivalent, since `Identifier` is a subtype of `Expression`? Therefore `Identifier` is already included in the current definition.

**Comment by EmpireWorld** [comment]
But i get **Identifier** type. so we should include it in the type. 

Using OR statement or bitwise symbol `||`.

like this:
```javascript
interface ClassMethod <: Function {
  type: "ClassMethod";
  key: Expression || Identifier; // Using OR
  kind: "constructor" | "method" | "get" | "set";
  computed: boolean;
  static: boolean;
  decorators: [ Decorator ];
}
```

**Comment by bakkot** [comment]
@EmpireWorld, it is already included in the type. Identifier is a subtype of Expression, so anywhere the spec calls for an Expression, an Identifier is also acceptable.

**Comment by EmpireWorld** [comment]
@bakkot Ohh. i found that. thanks.
