### ISSUE TITLE
dynamicImport + spread

### ISSUE THREAD

**Issue by jdalton** [babel/babylon#527]
I noticed in the babel repl that ...

```js
import(...[1])
```
is allowed, but according to [this](https://github.com/tc39/proposal-dynamic-import/issues/23#issuecomment-263742551) and [this](https://github.com/tc39/proposal-dynamic-import/issues/15#issuecomment-254008011) it should not.

**Comment by hzoo** [comment]
Hey @jdalton! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by jdalton** [comment]
🤖

**Comment by xtuc** [comment]
The `dynamicImport` Babylon plugin could also include the `objectRestSpread` plugin.

If this make sense in Babylon, I can make the PR.

**Comment by hzoo** [comment]
@xtuc The example ^ is array spread not objectRestSpread? @kesne

**Comment by kesne** [comment]
Yeah it reads arguments.length which is flawed for this reason. We could explicitly disallow spreads as the argument.

**Comment by kesne** [comment]
Whoops, just noticed there's a PR, awesome. I'll update the acorn plugin for Webpack. Thanks for finding this!
