### ISSUE TITLE
Allow Array as Rest Parameter Target in Arguments

### ISSUE THREAD

**Issue by danez** [babel/babylon#53]
``` js
((...[, y, z]) => console.log(y, z))(1, 2, 3);
```

> However, this code is valid in ES2016. It even works in Chrome 50.
> For more information, see https://esdiscuss.org/topic/ignoring-arguments

https://phabricator.babeljs.io/T7396

**Comment by hzoo** [comment]
Should test against these: https://github.com/tc39/test262/blob/master/test/language/rest-parameters/array-pattern.js
