### ISSUE TITLE
"id" property added to types that should never have id

### ISSUE THREAD

**Issue by andy-ms** [babel/babylon#535]
### Input Code

```js
() => {};
class C { m() {} } 
```

### Expected Behavior

No `id` property is added.

### Current Behavior

`id` is always present, but always set to `null`.

See `test/fixtures/es2015/uncategorized/176/actual.js` and `test/fixtures/es2015/uncategorized/113/actual.js`.

This behavior happens because `initFunction` sets `this.id = null;`. This would be easy to change, but I think that was causing errors in babel -- need to wait until #534 is resolved to confirm.

**Comment by hzoo** [comment]
Hey @andy-ms! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by danez** [comment]
By comparing this to all the other parses we do exactly the same as they do. Also in most cases it doesn't really matter if a prop is null or undefined.
