### ISSUE TITLE
import.meta: Stage 2

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#539]
> import.meta for stage 2 (Domenic Denicola) (@domenic)

## Info
Proposed at TC39 Meeting: [May 2017](https://github.com/tc39/agendas/blob/master/2017/05.md)
Spec Repo: https://github.com/tc39/proposal-import-meta
Spec Text: https://tc39.github.io/proposal-import-meta/

## Example

```js
(async () => {
  const response = await fetch(new URL("../hamsters.jpg", import.meta.url));
  const blob = await response.blob();

  const size = import.meta.scriptElement.dataset.size || 300;

  const image = new Image();
  image.src = URL.createObjectURL(blob);
  image.width = image.height = size;

  document.body.appendChild(image);
})();
```

## Parsing/ESTree
- [ ] make issue
- [x] Sounds pretty straightforward to make it a `MetaProperty` like `new.target`

```js
{
  "type": "MetaProperty",
  "meta": {
    "type": "Identifier",
    "name": "import"
  },
  "property": {
    "type": "Identifier",
    "name": "meta"
  }
}
```

- parsing `new.target` via `const metaProp = this.parseMetaProperty(node, meta, "target");` at 
 https://github.com/babel/babylon/blob/50694f99b12295b7515bb2c6c8f44b86a05deeca/src/parser/expression.js#L715
- dynamic import https://github.com/babel/babylon/blob/50694f99b12295b7515bb2c6c8f44b86a05deeca/src/parser/expression.js#L429

## Transform
- Not sure, maybe webpack should handle? Or in node?

**Comment by Kovensky** [comment]
How should the tree look like when `MemberExpression` are involved, like in `import.meta.foo`?

```
// super-like
MemberExpression {
  object: MemberExpression {
    object: Import {}
    property: Identifier { name: 'meta' }
  }
  property: Identifier { name: 'foo' }
}
```
```
// new.target-like
MemberExpression {
  object: MetaProperty {
    meta: Identifier { name: 'import' }
    property: Identifier { name: 'meta' }
  }
  property: Identifier { name: 'foo' }
}
```

ESTree specifically defined an `Import` node expecting it to be used like `super` in the future.

https://github.com/estree/estree/blob/master/experimental/import-expression.md

**Comment by bakkot** [comment]
I'd vote for making it like `new.target`, definitely. That's certainly how it's spec'd, and `import.somethingElse` is not grammatical.

I believe ESTree's import expression is just to support dynamic import: `import("whatever")` is legal. It has nothing to do with this proposal from the AST's perspective, despite the visual similarity.

**Comment by Kovensky** [comment]
The reasoning for _naming_ it `Import` instead of `DynamicImport` was because of the similarity to `Super` when it got meta-properties added.

It would be nice to be able to have `Import {}` as the `MetaProperty`'s `meta`, instead of an `Identifier { name: 'import' }` though.

**Comment by bakkot** [comment]
I'm sad I wasn't paying attention when that decision was made, then. `import.meta` is a thing of its own, and has nothing to do with `import("")` except that they have one token in common.

Not a big fan of the `MetaProperty` node type either, come to that. `new.target` and `import.meta` really ought to be their own node types (possibly subtypes of `MetaProperty`, I guess, but not involving any strings anywhere). Since that ship has apparently sailed, I think `Identifier { name: 'meta' }` is more in keeping with `new.target` than `Import {}` is.

**Comment by hzoo** [comment]
@babel-bot move to babel/babel

**Comment by hzoo** [comment]
Hey @hzoo! I've [moved your issue](https://github.com/babel/babel/issues/5832) to the correct repository. Please make sure to keep an eye on the new issue for the latest information.
