### ISSUE TITLE
BigInt: Stage 2

### ISSUE THREAD

**Issue by littledan** [babel/babylon#569]
Champion: @littledan 
Spec Repo: https://github.com/tc39/proposal-bigint
Spec Text: https://tc39.github.io/proposal-bigint
Slides (to Stage 3 at May TC39 Meeting): https://docs.google.com/presentation/d/1lrcjQzIFgdUXczeeAzs4GkTXJsRQU21UhtmXef70Qic/edit#slide=id.p

## Parser

- Similar to https://github.com/babel/babylon/issues/538, we'll need to modify the tokenizer to accept `10n` 
as a valid number. (Check that [PR](https://github.com/babel/babylon/pull/541))
- From a syntactic perspective, the only thing added is numeric literals of the form `987235987032n`. These permit hexadecimal, octal and binary prefixes, but no exponential form, and no decimal place. See the grammar [in this section of the proposed spec](https://tc39.github.io/proposal-bigint/#sec-grammar-change).

## Transform

- All arithmetic operations and comparisons should be replaced by calls to functions which provide the appropriate behavior depending whether arguments are BigInts or Numbers.
  - The transform is slow, so it will really be more of a toy rather than something that should be used in production. For this reason, I'd argue it should be left out of Babel presets.
- Polyfill needed--ideally, this would be a thin wrapper around another BigNum library from npm. There are just a few methods to support. Some functions will have to be a bit different to get close to the right behavior, for example, `valueOf()` should throw a TypeError, so that implicitly casting to Number throws a TypeError, even if it would really return the BigInt. Additionally, the polyfill needs BigInt64Array and DataView operations.

**Comment by hzoo** [comment]
Hey @littledan! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by wdhorton** [comment]
I'd like to take on this issue!

**Comment by amilajack** [comment]
> All arithmetic operations and comparisons should be replaced by calls to functions which provide the appropriate behavior depending whether arguments are BigInts or Numbers.

I've done some work on this in a [babel plugin that prevents coercion in JS](https://github.com/amilajack/babel-plugin-fail-explicit). Here's the [related code for that](https://github.com/amilajack/babel-plugin-fail-explicit/blob/master/src/index.js#L127-L155)

**Comment by littledan** [comment]
@wdhorton Let me know if you want any help with reviews, interpreting the spec, etc!
