### ISSUE TITLE
[feature request] Support Flow syntax `export type * from`

### ISSUE THREAD

**Issue by echenley** [babel/babylon#570]
Apologies if there is already an issue for this. I searched in both the babel monorepo and here and could not find anything.

[Flow v0.45.0](https://github.com/facebook/flow/releases/tag/v0.45.0) introduced the `export type * from` syntax. This syntax is still unfortunately not supported by babel, which means for many use cases it is still unusable.

The * syntax is extremely useful for type libraries, which may need to re-export types across multiple files. Currently that process involves duplicating all exports at each level.

**Comment by hzoo** [comment]
Hey @echenley! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by existentialism** [comment]
@echenley https://github.com/babel/babylon/issues/617 landed support, should be released soon!
