### ISSUE TITLE
Transforming large json file, JavaScript heap out of memory

### ISSUE THREAD

**Issue by krsjoseph** [babel/babylon#577]
The json file is pretty large around 30mb. 
I keep getting the error below, tired different versions of node

<img width="1497" alt="screen shot 2017-06-13 at 9 25 47 pm" src="https://user-images.githubusercontent.com/1019869/27111850-eec1bc06-5080-11e7-848b-4de4f720b47d.png">

### Input Code

```js
import React, { Component } from "react";
import { View, Text, StyleSheet, ListView } from "react-native";
import data from './data.json'

class List extends Component {
  constructor(props) {
    super(props);
    const ds = new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2
    });
    this.state = {
      dataSource: ds.cloneWithRows(data)
    };
  }

  render() {
    return (
      <View style={styles.container}>
        <ListView
          dataSource={this.state.dataSource}
          renderRow={rowData => <Text>{rowData}</Text>}
        />
      </View>
    );
  }
}


export default List;

```

### Babylon/Babel Configuration

```js
{
  "presets": ["react-native"]
}
```

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.17.2
| node             | 8.1.0, 7.1.0
| npm              | 5.0.3
| Operating System | macOS 10.12.5

**Comment by hzoo** [comment]
Hey @krsjoseph! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by jridgewell** [comment]
Why are you transforming a json file?

**Comment by hzoo** [comment]
You can exclude .json files in babel-loader or filter out the extension since it doesn't need to be processed by Babel

**Comment by krsjoseph** [comment]
@jridgewell I'm just importing it into a react component to be used as an array.

**Comment by nicolo-ribaudo** [comment]
You don't need to transpile it with Babel: Babel is just for JavaScript source. You should exclude that file from the Babel (using the "ignore" option in your `.babelrc`) and let react native load the file.

**Comment by krsjoseph** [comment]
Thanks! @hzoo, @jridgewell @nicolo-ribaudo

**Comment by jridgewell** [comment]
It'd be cool to investigate further (anything that reduce's Babylon's memory footprint is a win), but I don't know if we'll ever get to the point of being able to transform a 30mb file.

**Comment by hzoo** [comment]
All good! Not sure why it's not ignoring it by default then?

**Comment by krsjoseph** [comment]
@hzoo I'm gonna submit a PR over at the react native repo to include the ignore by default

**Comment by jridgewell** [comment]
Can you post the JSON file? Or a sample of it (we don't need 10000 items of the array, just the first couple, any strings can just be random, etc)

**Comment by krsjoseph** [comment]
Example object.

It's basically ~79800 of these records.

```json
[{
	"_id": "593b7c28c5adbaa75c0833e5",
	"firstname": "Krs",
	"lastname": "Joseph",
	"dob": "1993-09-10T04:00:00.000Z",
	"uuid": "66738cfdc13842290c732372b0c365812d8510048bf8fa1afb2e78fb736c6c33",
	"companyName": null,
	"isGuardianMember": false,
	"insuranceCompany": "The Beacon Insurance Company Limited",
	"__v": 0,
	"isRegistered": false
}]

```
