### ISSUE TITLE
Significant but hard-to-find bug in parsing arrow functions

### ISSUE THREAD

**Issue by Lucretiel** [babel/babylon#58]
As of a recent release (Don't know when, exactly, but this issue broke code that was working fine around June 4), babylon's parsing of arrow functions has broken in a very peculiar way. When babylon encounters the following pattern:

```
<some expression> :
    <a parenthesized arrow expression> ?
    <an unparenthesized arrow expression>
```

It reports an error parsing the parenthesized arrow expression:

```
Module build failed: SyntaxError: <path to file>: Assigning to rvalue (23:3)
```

For example:

```
let x = foo() ?
    (value => true) :
    value => false
```

The contents of the condition don't seem to matter, nor does parenthesizing the entire conditional expression. However, if the parenthesis around the first arrow function are removed, or parenthesis are added to the second arrow function, or either arrow function is something other than an arrow function, it is parsed fine. This specific pattern is the only one that triggers the error.

For what it's worth, I'm running babylon via babel via webpack, but the stack trace I get is entirely from babylon.

This seems implausible, I know, so I've created a git repo which reproduces the error, available here:

https://github.com/Lucretiel/babylon-error

The specific file I'm trying to pack is [index.js](https://github.com/Lucretiel/babylon-error/blob/master/index.jsx) with no dependencies or requires. The raw output from `webpack` is in [build_result](https://github.com/Lucretiel/babylon-error/blob/master/build_result).

**Comment by Lucretiel** [comment]
Quick follow up: I've just discovered that this bug ONLY manifests itself if the `react` babel plugin is being used.

**Comment by hzoo** [comment]
Ok, so it only happens when flow/jsx parsing is on

**Comment by danez** [comment]
I just did a git bisect and this is the result:
> d15a2310cd405cb0bbfae1fbeb12d8ffbd4e28cb is the first bad commit

I will have a look what my change broke.

**Comment by danez** [comment]
After digging around I also found this case which is not working anymore:
```
a ? (b): c => d
```

Because babylon with flow now sees the "valid-looking" arrow function `(b): c => d`.

Thinking about reverting my change and then reopening the other bug and redoing the fix.
