### ISSUE TITLE
Regex unicode escape flags

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babylon#582]
This code should **not** be considered valid:
```js
/[P QR]/\u0067
```

### Spec
https://tc39.github.io/ecma262/#prod-RegularExpressionFlags
```
RegularExpressionFlags::
    [empty]
    RegularExpressionFlags IdentifierPart 
```

https://tc39.github.io/ecma262/#sec-literals-regular-expression-literals-static-semantics-early-errors
```
11.8.5.1 Static Semantics: Early Errors
    RegularExpressionFlags :: RegularExpressionFlags IdentifierPart
        It is a Syntax Error if IdentifierPart contains a Unicode escape sequence.
```

I also looked at Annex B and Annex E, but I couldn't find anything that makes that code valid.

### 😱 
There is a test that ensures that babylon parses it correcly:
https://github.com/babel/babylon/blob/master/test/fixtures/core/uncategorised/108/actual.js

| software         | version
| ---------------- | -------
| Babylon          |  master

**Comment by hzoo** [comment]
Hey @nicolo-ribaudo! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
