### ISSUE TITLE
Better error message for duplicated params in arrow functions

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babylon#591]
### Input Code

```js
(a, a) => b
```

### Expected Behavior
Babylon should throw something like `Argument name clash in arrow function`

### Current Behavior
`Argument name clash in strict mode` (even if that code is not in strict mode)

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.14, 6.25.0

**Comment by hzoo** [comment]
Hey @nicolo-ribaudo! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
