### ISSUE TITLE
SyntaxError on arrow func returning jsx without parens

### ISSUE THREAD

**Issue by existentialism** [babel/babylon#593]
As reported in: https://github.com/prettier/prettier/issues/2286

Regression from https://github.com/babel/babylon/pull/578:

```jsx
const fail = (): X => <x />; // SyntaxError: Unexpected token, expected , (2:26)
```

/cc: @nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
I can look at this bug now
