### ISSUE TITLE
Flow - type cast a parenthesized expression to a function

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babylon#607]
### Input Code

```js
((a => b) : c => d)
```

### Babylon/Babel Configuration

```js
{
  "plugins": [ "flow" ]
}
```

### Expected Behavior

It should be parsed as an arrow function whose type is `c => d`

### Current Behavior
`Invalid left-hand side in arrow function parameters`

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.12

https://astexplorer.net/#/gist/b75e622f22194ec04bbecf2aae6859a8/latest

**Comment by hzoo** [comment]
Hey @nicolo-ribaudo! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by nicolo-ribaudo** [comment]
The properties introduced by #596 (`noArrowParamsConversionAt` and `noArrowAt`) can probably help to fix this issue.
