### ISSUE TITLE
function.sent as an expression statement.

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babylon#611]
### Input Code

```js
function* gen() {
  (function.sent);
  function.sent;
}
```

### Babylon/Babel Configuration

```js
{
  "plugins": [ "functionSent" ]
}
```

### Expected Behavior
The second and third lines should be parsed in the same way.

Ref: https://github.com/allenwb/ESideas/issues/13#issuecomment-313559409

### Current Behavior
The third lines throws something like "Unexpected ."

https://astexplorer.net/#/gist/5d4d44becbe4b3236be7a2a2f8b9e81c/latest

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.16

**Comment by hzoo** [comment]
Hey @nicolo-ribaudo! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
