### ISSUE TITLE
Dot after "function" inside a generator doesn't throw

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babylon#612]
### Input Code

```js
function* foo() {
  (function.fn() {});
}
```

https://astexplorer.net/#/gist/4a6290c9416046ef323f5cef1202e28f/latest

### Babylon/Babel Configuration

The `functionSent` plugin must be disabled.

### Expected Behavior

It should throw

### Current Behavior

The dot is ignored

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.16

**Comment by hzoo** [comment]
Hey @nicolo-ribaudo! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
