### ISSUE TITLE
Problem with comment attachment when `estree` plugin is enabled

### ISSUE THREAD

**Issue by hegemonic** [babel/babylon#619]
Some comments are not attached correctly when all of the following things are true:

+ The `estree` plugin is enabled
+ The JS file contains a `'use strict';` directive and at least one line of code
+ There are comments after the last line of code in the file

### Input Code

```js
'use strict';

module.exports = {};

/**
 * @external foo
 */
```

### Babylon/Babel Configuration

```js
{
    ranges: true,
    sourceType: 'module',
    plugins: [
        'asyncGenerators',
        'bigInt',
        'classPrivateProperties',
        'classProperties',
        'decorators2',
        'doExpressions',
        'dynamicImport',
        'estree',
        'exportExtensions',
        'functionBind',
        'functionSent',
        'importMeta',
        'jsx',
        'numericSeparator',
        'objectRestSpread',
        'optionalChaining'
    ]
}
```

### Expected Behavior

All of the comments at the end of the file are attached to the last node in the `Program` node's body.

### Current Behavior

All of the comments at the end of the file are incorrectly attached to the `ExpressionStatement` node for the `'use strict';` directive. [Example](https://astexplorer.net/#/gist/3ab9c8567c9d0a9679e5055eac3d2471/15067337efba599e4417dff5976734d8e2b7eb86).

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.16
| node             | 8.1.3
| npm              | 5.2.0
| Operating System | macOS Sierra 10.12.5

**Comment by hzoo** [comment]
Hey @hegemonic! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
