### ISSUE TITLE
Very slow parsing of large JSON file with flow plugin

### ISSUE THREAD

**Issue by spicyj** [babel/babylon#62]
With the flow plugin, https://github.com/babel/babylon/pull/19 seems to have regressed parsing performance on really giant files.

Before #19 (e6c11a06), this finished in about 0.5 seconds. After, it takes hours:

```
curl -O https://raw.githubusercontent.com/mbostock/topojson/master/examples/world-50m.json
node -e 'require("/path/to/babylon").parse("(" + require("fs").readFileSync("world-50m.js", "utf-8") + ")", { plugins: [ "flow" ] })
```

There is no problem if the flow plugin is disabled. It looks like the `this.state.clone()` calls get slower and slower as it parses more of the file. Maybe the total runtime is `O(n^3)` in the size of the file? That would put us at about 470 hours to parse the file based on a bit of logging I did.

This is blocking me from updating Facebook to use a newer Babylon. (Actually, the reason I want to upgrade is to get the fix from #19…)

**Comment by danez** [comment]
Thanks for reporting, I will have a look later today.

**Comment by danez** [comment]
I created a PR with a fix for this. Trying to get out a release asap.
