### ISSUE TITLE
export async;

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babylon#620]
### Input Code

```js
export async;
```
https://astexplorer.net/#/gist/08a46bcd5b3c2260a3e470a774c20cce/latest

### Expected Behavior
Is should throw "Unexpected token, expected function (1:12)"

### Current Behavior
It is parsed as an export declaration with an expression statement

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.16

**Comment by hzoo** [comment]
Hey @nicolo-ribaudo! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
