### ISSUE TITLE
`a <!-- b` in modules are actually equivalent to `a < !(--b)`

### ISSUE THREAD

**Issue by isiahmeadows** [babel/babylon#622]
See: https://github.com/tc39/ecma262/issues/949

An error is generated for `a <!-- b` with `scriptType: "module"`, when it should parse like `a < !(--b)`.

**Comment by hzoo** [comment]
Hey @isiahmeadows! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
