### ISSUE TITLE
Parses invalid code

### ISSUE THREAD

**Issue by jdmota** [babel/babylon#623]
### Input Code

```js
let a = 1 %* 1;
a %*= 1;
```
http://astexplorer.net/#/gist/25c78c4032e0bb15be28bb94f94604d7/100f776850d9a7f969d565e5442da4b391efd06a

### Expected Behavior

Throw "Unexpected token".

### Current Behavior

Parses without failing.

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7
| node             | 
| npm              | 
| Operating System | 

I can reproduce in http://astexplorer.net/ (which is using babylon7-7.0.0-beta.12), but I believe the problem still exists in the lastest version.

I believe the problem lies in [src/tokenizer/index.js#L388](https://github.com/babel/babylon/blob/master/src/tokenizer/index.js#L388)

**Comment by hzoo** [comment]
Hey @jdmota! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by jridgewell** [comment]
We need to update https://github.com/babel/babylon/blob/master/src/tokenizer/index.js#L394-L399 to:

```js
if (code === 42 && next === 42) {
  //...
}
