### ISSUE TITLE
Wrong parsing of new.target inside an arrow function

### ISSUE THREAD

**Issue by droooney** [babel/babylon#640]
Input:

```js
const foo = () => {
  console.log(new.target);
};
```

Expected behaviour: a syntax error (Chrome throws "new.target expression is not allowed here", Firefox throws "new.target only allowed within functions").

Actual behaviour: parsed.

**Comment by hzoo** [comment]
Hey @droooney! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
