### ISSUE TITLE
Wrong parsing of new.target inside function arguments

### ISSUE THREAD

**Issue by droooney** [babel/babylon#641]
babylon version: **6.17.4** (the same for v7).

Input:

```js
function Foo(bar = new.target) {}
```

Expected behaviour: parsed.

Actual behaviour: a syntax error is thrown.

The behaviour for arrow functions should differ though, because function arguments are inside the function body (see #640).

**Comment by hzoo** [comment]
Hey @droooney! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
