### ISSUE TITLE
Flow: variance representation - flow compatibility

### ISSUE THREAD

**Issue by fkling** [babel/babylon#645]
### Input Code
```js
import React from 'react';

type Value = {|
  +testing: boolean,
|};

type Props = {
    value: Value,
};

class Component extends React.Component {
  props: Props;
}
```

### Babylon/Babel Configuration

```js
var options = {
  sourceType: 'module',
  strictMode: false,
  plugins: [
    'jsx',
    'flow',
    'estree',
    'doExpressions',
    'objectRestSpread',
    'decorators',
    'classProperties',
    'exportExtensions',
    'asyncGenerators',
    'functionBind',
    'functionSent',
    'dynamicImport',
  ],
};
```

### Expected Behavior

Should the representation of type annotations follow the one flow uses? If yes, they use a string value for variance:

```
          {
            "type": "ObjectTypeProperty",
            "key": {},
            "value": {},
            "optional": false,
            "static": false,
            "variance": "plus",
            "kind": "init"
          }
```

whereas Babylon uses a `Variance` node:

```
            {
              "type": "ObjectTypeProperty",
              "key": {},
              "static": false,
              "kind": "init",
              "value": {},
              "variance": {
                "type": "Variance",
                "kind": "plus"
              },
              "optional": false
            }
```

`recast`/`ast-types` doesn't understand the `Variance` node, which is a problem for `react-docgen`. I'm just wondering where this should be fixed/changed. Here or in `ast-types`?

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  v7.0.0-beta.17

**Comment by hzoo** [comment]
Hey @fkling! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by hzoo** [comment]
relevant issue: https://github.com/babel/babel/issues/4722?

**Comment by fkling** [comment]
Oh sorry, I didn't look for closed issues 😞 . So is it still the plan that flow will switch to a `Variance` node eventually? I'm a bit confused. cc @samwgoldman 

I guess ast-types should be updated in the meantime then.

**Comment by danez** [comment]
https://github.com/facebook/flow/issues/4789
