### ISSUE TITLE
Parse until error, still retrieve parsed file info

### ISSUE THREAD

**Issue by ericbiewener** [babel/babylon#655]
Even when encountering an error, I'd like to be able to get the parsed file data up to that point. Perhaps this could be implemented as a configuration option, in which case the results of `parse()` would include an `error` key with the error data rather than actually throwing an error.

**Comment by hzoo** [comment]
Hey @ericbiewener! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by loganfsmyth** [comment]
https://github.com/babel/babylon/issues/347 would probably address your request in a more general way. I think it's a reasonable feature request, but it's hard to say if there is anyone interested in working on that at the moment.
