### ISSUE TITLE
6.8.3 Changing checkbox input's checked attribute to null does not uncheck it

### ISSUE THREAD

**Issue by thomkrillis** [babel/babylon#66]
I am building a React project with webpack and noticed that after updating from 6.8.2 to 6.8.3 that setting a checkbox input's checked attribute from whatever is was before to null does not result in the checkbox unchecked. It seems that if it started checked, it will stay checked when set to null, but if it started null, it will appear unchecked until it is clicked.

I expected that setting an attribute to null would be the equivalent of removing that attribute. Is that not the case?

Also, it may be possible that this change was caused by something other than babylon updating, but not as far as I can tell.

Example of the React snippet I am referring to:
`<input type="checkbox" checked={condition ? "checked" : null} />`

**Comment by RReverser** [comment]
Well, first of all, I don't see how this can be possibly related to a code parser.

Second, `checked` in React is a boolean and takes `true` / `false` and not HTML-like `"checked"` string and certainly not `null`.

**Comment by danez** [comment]
Maybe it was because of the recent react update? But I also can't see a relation to babylon.

**Comment by thomkrillis** [comment]
Yep, just confirmed this issue wasn't caused by babylon updating. Guess I jumped the gun opening this ticket.

Thanks for the replies.
