### ISSUE TITLE
Disallow binding patterns of arrays or objects in BindingRestProperty

### ISSUE THREAD

**Issue by gsathya** [babel/babylon#661]
### Input Code

```js
let {...{}} = {};
```

### Babylon/Babel Configuration

stage3-preset

### Expected Behavior
SyntaxError: `...` must be followed by an identifier in declaration contexts

### Current Behavior
No error

### Your Environment

[repl](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=stage-3&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code_lz=DYUwLgBA3gdHUF8EQLzQQbiA&playground=true)

**Comment by danez** [comment]
This was already fixed and the latest versions of 6.x and 7.x both work for me. Not sure what the repl is using though.

**Comment by gsathya** [comment]
> Also the repl seems to work for me successfully.

Does the link I pasted work? It doesn't throw a syntax error for me.

**Comment by danez** [comment]
Ohh I mixed something up, I thought you expected it to pass and got an error, but you said the opposite. :)

**Comment by hzoo** [comment]
Yeah it was already an error in 6.x and I remember at the meeting we decided to make it actually an error but it got "fixed" lol so need to revert in a sense

**Comment by Andarist** [comment]
Can be closed, PR already merged in :)

**Comment by hzoo** [comment]
Closed by https://github.com/babel/babylon/pull/670, thanks @Andarist!
