### ISSUE TITLE
Disallow nested destructuring assignment with rest properties

### ISSUE THREAD

**Issue by gsathya** [babel/babylon#667]
### Input Code

```js
 ( {...{}} = {} ) 
```

### Babylon/Babel Configuration

stage3 preset

### Expected Behavior

SyntaxError: `...` must be followed by an assignable reference in assignment contexts

### Current Behavior

No error 

### Your Environment
[repl](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=stage-3&targets=Node-4&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code_lz=BQbwdBIL5QBAvLaBKIA&playground=true)

**Comment by nicolo-ribaudo** [comment]
Isn't this #661?

**Comment by gsathya** [comment]
> Isn't this #661?

No, that's for binding pattern. This is for assignment pattern.

**Comment by Andarist** [comment]
Is this still for grabs? I would like to work on it, but aint sure if noone has started yet.

**Comment by nicolo-ribaudo** [comment]
Go for it 👍
You might also want to look for a fix for #661

**Comment by Andarist** [comment]
Yeah, if I do this one I'll definitely look into other one, just don't want to block the other one yet, cause Im just diving into babylon for the first time :)

**Comment by nicolo-ribaudo** [comment]
If you need any help, you can join our slack: https://slack.babeljs.io/

**Comment by Andarist** [comment]
Can be closed, PR already merged in.
