### ISSUE TITLE
Diff in range data of Program vs other parsers for leading newline(s)

### ISSUE THREAD

**Issue by JamesHenry** [babel/babylon#673]
Eurgh... 😅 

I am honestly not sure on what to suggest to address this, but if you take this really simple source (**the leading newline is key but not that clear in the codeblock**):

### Input Code

```js

function foo() {

}

```

You end up with different range data for the `Program` node across the different parsers.

Please see: http://astexplorer.net/#/gist/c336be172990d7b467d1ed3dbc1882ee/215640e9e6eece750582ef00b16a884a5c66530a

...and take a look at the different parsers.

I found this when running AST comparison tests between `babylon` and `typescript-eslint-parser` (which behaves like `espree`/`esprima`) for JS source fixtures.

The diff essentially boils down to the inclusion of the leading newline (or not in the case of babylon):
```
      "column": 0,
           "line": 1,
         },
       },
       "range": Array [
    -    1,
    +    0,
         28,
       ],
       "sourceType": "script",
       "type": "Program",
     }
```

I do have the ESTree plugin enabled, so I would theoretically expect to see parity here.

**Comment by hzoo** [comment]
Hey @JamesHenry! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by JamesHenry** [comment]
Same thing with leading comments:

```js
/* foo */
if (/* bar */  a) {}
```

It appears **Espree, Esprima, Flow and Recast** have one view of the world, **Acorn and Babylon** have another.

Espree:
```js
{
  "type": "Program",
  "start": 0,
  "end": 31,
  "range": [
    10,
    30
  ],
...
```

Esprima:
```js
{
  "type": "Program",
  "range": [
    10,
    30
  ]
...
```

Flow:
```js
{
  "type": "Program",
  "range": [
    10,
    30
  ],
...
```

Recast:
```js
{
    "type": "Program",
    "range": [
      10,
      30
    ],
...
```
-------

Acorn:
```js
{
  "type": "Program",
  "start": 0,
  "end": 31,
  "range": [
    0,
    31
  ],
...
```

Babylon:
```js
{
    "type": "Program",
    "start": 0,
    "end": 31,
    "range": [
      0,
      31
    ],
...
```

**Comment by JamesHenry** [comment]
It seems the same groupings of parsers hold true for observed differences in `TemplateLiteral.quasis` location data too...

```js
`42`;
```

Espree:
```js
{
   "quasis": [{
      "type": "TemplateElement",
      "start": 1, // This combined with the range seems like a bug?
      "end": 3,  // This combined with the range seems like a bug?
      "range": [
         0,
         4
      ],
...
```

Esprima:
```js
{
   "quasis": [{
      "type": "TemplateElement",
      "range": [
         0,
         4
      ],
...
```

Flow:
```js
{
   "quasis": [{
      "type": "TemplateElement",
      "range": [
         0,
         4
      ],
...
```

Recast:
```js
{
   "quasis": [{
      "type": "TemplateElement",
      "range": [
         0,
         4
      ],
...
```
-------

Acorn:
```js
{
   "quasis": [{
      "type": "TemplateElement",
      "start": 1,
      "end": 3,
      "range": [
         1,
         3
      ],
...
```

Babylon:
```js
{
   "quasis": [{
      "type": "TemplateElement",
      "start": 1,
      "end": 3,
      "range": [
         1,
         3
      ],
...
```
