### ISSUE TITLE
npmjs missing dist version 7.0.0-beta.0-ranges

### ISSUE THREAD

**Issue by beck** [babel/babylon#677]
A bit nuanced, discovered because I was using an old version of npm via a private repo server that proxies to npmjs.com:

Installing these deps:
```
  "dependencies": {
    "babylon": "~7.0.0-beta.0"
  }
```

NPM tried to install version `7.0.0-beta.0-ranges`

Which is present in:
```
$ npm info babylon --json
{
  "name": "babylon",
  "versions": [
    "7.0.0-beta.0",
    "7.0.0-beta.0-ranges"
  ]
}
```

But does not have a release associated with it:
```
$ npm install babylon@7.0.0-beta.0-ranges
> ERR! notarget a package version that doesn't exist.
```

**Comment by hzoo** [comment]
Hey @beck! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by loganfsmyth** [comment]
Does `npm info babylon --json` show the `-ranges` version when you point it at the main registry? I don't see that on my machine, but I don't know if it's your old npm version, or your registry mirror doing that.

**Comment by beck** [comment]
My output:
```
$ npm info babylon --json | grep 0-ranges
    "7.0.0-beta.0-ranges": "2017-02-15T23:43:49.112Z",
```

Just to double check I'm configured against npmjs:
```
$ npm info babylon --json --ddd
...
npm sill mapToRegistry registry https://registry.npmjs.org/
npm verb request uri https://registry.npmjs.org/babylon
...
````

**Comment by beck** [comment]
My mistake, that tag is coming from the `time` block, not `versions`.
