### ISSUE TITLE
Add tests for do expressions

### ISSUE THREAD

**Issue by danez** [babel/babylon#681]
We currently have not a single test for `doExpressions`. We should add some tests to babylon.
Can take the examples from the official gist.

Tests should go into `test/fixtures/experimental/do-expressions/`

https://gist.github.com/dherman/1c97dfb25179fa34a41b5fff040f9879

**Comment by echo304** [comment]
Let me tackle this issue 🖐

**Comment by jridgewell** [comment]
Closed by #688.
