### ISSUE TITLE
ESTree plugin not able to convert StringLiteral in TS shorthand module dec

### ISSUE THREAD

**Issue by JamesHenry** [babel/babylon#683]
When using the TypeScript and ESTree plugins together, the `id` of the TypeScript shorthand module declaration source below is coming through as a `StringLiteral`, instead of a `Literal`.

### Input Code

```ts
declare module "hot-new-module";
```

### Babylon/Babel Configuration

```js
{
  "sourceType": "module",
  "plugins": ["typescript", "estree"]
}

```

### Current (red) vs Expected (green) Behavior
```diff
{
  "type": "File",
  "start": 0,
  "end": 32,
  "loc": {
    "start": {
      "line": 1,
      "column": 0
    },
    "end": {
      "line": 1,
      "column": 32
    }
  },
  "program": {
    "type": "Program",
    "start": 0,
    "end": 32,
    "loc": {
      "start": {
        "line": 1,
        "column": 0
      },
      "end": {
        "line": 1,
        "column": 32
      }
    },
    "sourceType": "module",
    "body": [
      {
        "type": "TSModuleDeclaration",
        "start": 0,
        "end": 32,
        "loc": {
          "start": {
            "line": 1,
            "column": 0
          },
          "end": {
            "line": 1,
            "column": 32
          }
        },
        "id": {
-        "type": "StringLiteral",
+        "type": "Literal",
          "start": 15,
          "end": 31,
          "loc": {
            "start": {
              "line": 1,
              "column": 15
            },
            "end": {
              "line": 1,
              "column": 31
            }
          },
          "value": "hot-new-module",
          "raw": "\"hot-new-module\""
        },
        "declare": true
      }
    ]
  }
}
```

**Comment by hzoo** [comment]
Hey @JamesHenry! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by JamesHenry** [comment]
I have a fix ready for this

**Comment by existentialism** [comment]
Fixed by https://github.com/babel/babylon/pull/684, thanks @JamesHenry!
