### ISSUE TITLE
is there something wrong?

### ISSUE THREAD

**Issue by atmjs** [babel/babylon#687]
https://github.com/babel/babylon/blob/d0c7d7a8c7534f9f766d72435247339c0aa3d365/src/parser/statement.js#L893

is it should to be :  `!this.hasPlugin("decorators2")' ?

**Comment by hzoo** [comment]
Hey @atmjs! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by nicolo-ribaudo** [comment]
It's correct: only the decorators2 plugin disallows decorator on non-method class members, so we need to check if the decorator has been parsed using that plugin
