### ISSUE TITLE
How to get started with learning about babylon

### ISSUE THREAD

**Issue by pudility** [babel/babylon#690]
I am not sure if this is the right place for this question, so please let me know if I should put it somewhere else. I am really new to Babylon but I would like to learn more about it, and maybe even work on it/contribute to it a little. I downloaded the sources from this Github repo, and played around with it some, however I am wondering if any of you more experienced users could tell me what would be good to get started with so that I could learn about how it works.

Thank you so much!

**Comment by hzoo** [comment]
Hey @pudility! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by existentialism** [comment]
@pudility Hey there 👋 ! In general, beyond checking out the obvious (like the README, CONTRIBUTING, etc)... the [babel-handbook](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md) by @thejameskyle is a great resource for both a very high-level overview of Babylon and understanding its relationship with Babel.

For me personally, I did the boneheaded approach of just diving in the code and spending tons of time experimenting with [astexplorer](https://astexplorer.net/), which you will find to be an invaluable resource.

I know all of us on the team are definitely interested in anything we're missing/lacking when it comes to getting new users/contributors onboard, so definitely let us know! As always, if you have any questions, feel free to join our [slack channel](http://slack.babeljs.io/).

Always happy to help in any way we can, and looking forward to your contributions!

(Going to close this for now, as there's nothing really actionable.)

**Comment by pudility** [comment]
Thank you so much! I will make sure to check out all of those resources. I really appreciate you taking the time to help me as a new contributor (hopefully).
