### ISSUE TITLE
Flow declarations don't check for declare name

### ISSUE THREAD

**Issue by danez** [babel/babylon#71]
Currently declares inside `declare module` don't need to start with a `declare` name. For example this is valid code:
```
declare module A {
  placeanythinghere var a:number
}
```

Flow itself also parses it. I know flow tries not to fail in most situations, but do we also want to do that in babylon?
It could be easily changed and there is already a [todo](https://github.com/babel/babylon/blob/master/src/plugins/flow.js#L101), but I'm not sure what the wanted way currently is.

@jeffmo, @kittens : What are your thoughts on this?

**Comment by jeffmo** [comment]
This is a parse error in Flow -- should probably be in Bablyon, too.

https://astexplorer.net/#/pNxlnaH77f

**Comment by danez** [comment]
Ah, I never checked the errors array. Stupid me.

**Comment by jeffmo** [comment]
Well, I think the other half of this issue is still relevant: Babylon should probably error

**Comment by danez** [comment]
Yes I opened #73
