### ISSUE TITLE
does not support decorators and generator

### ISSUE THREAD

**Issue by jamieYou** [babel/babylon#721]
<img width="726" alt="2017-08-14 2 25 35" src="https://user-images.githubusercontent.com/19544032/29260442-7b1c4684-80fc-11e7-9665-2fd28c7e5065.png">

| software         | version(s)
| ---------------- | -------
| babel-core            |  6.25.0
| babylon            |  6.18.0
| node             |  8.0.0
| npm              |  5.0.0
| Operating System |

**Comment by hzoo** [comment]
Hey @jamieYou! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by nicolo-ribaudo** [comment]
Hi, this bug has been fixed in the `decorators2` plugin.
