### ISSUE TITLE
Specify ecma version before parsing

### ISSUE THREAD

**Issue by Alphapage** [babel/babylon#722]
Hello,

Is there a way to tell babylon to parse only es2015 and rejects when es2016 syntaxes are reached ?

Thank you in advance for your help.

**Comment by hzoo** [comment]
Hey @Alphapage! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by nicolo-ribaudo** [comment]
No, there isn't. Babylon parses standard JavaScript by default, and you can opt-in to parse other syntax extensions; there isn't a way to specify that you don't want some JavaScript features.

I'd suggest traversing the AST (using babel-traverse, a Babel plugin visitor or any other traverser) to check that there isn't the nodes you want to forbid.

**Comment by loganfsmyth** [comment]
Alternatively if you're not using any experimental syntax, you can always use ESLint to enforce this kind of thing.

**Comment by hzoo** [comment]
https://eslint.org/docs/rules/no-restricted-syntax, https://github.com/amilajack/eslint-plugin-compat

**Comment by Alphapage** [comment]
Thank you very much those infos. You help me a lot.
Best regards.

**Comment by cletusw** [comment]
Let me make sure I understand this correctly. Every time babylon updates to support a new version of ECMAScript, I now have to make sure to add each language feature in that version to `no-restricted-syntax` (`eslint-plugin-compat` doesn't seem to catch async functions) or else they will silently succeed at build time and break any old browsers that I support?

**Comment by nicolo-ribaudo** [comment]
Yes, it ships new standards like a browser does: the browsers you use to debug your code may silently add support for the latest standard, so you won't notice you are using new JS features and it will break in older browsers.

**Comment by cletusw** [comment]
Right, but that seems antithetical to babel's purpose of allowing me to write whatever I want and transpiling down to lowest-common-denominator code. If I've set my babel config to only load `babel-preset-es2015` then it seems reasonable to expect that anything beyond that would fail to build.
