### ISSUE TITLE
Object rest spread doesn't work in non-declarations

### ISSUE THREAD

**Issue by tolmasky** [babel/babylon#723]
As far as I know, "{ ...rest } = x" should work fine. It seems to work in node 8. However, Babylon only allows it in declarations (let/var, etc).

### Input Code

https://runkit.com/tolmasky/spread-broken-babylon-current
https://runkit.com/tolmasky/spread-broken-babylon-beta

```js
parse("{ ...rest } = x", { plugins: ["objectRestSpread"] })
```

### Babylon/Babel Configuration

```js
{ plugins: ["objectRestSpread"] }
```

### Expected Behavior

Should parse.

### Current Behavior

Throws.

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.18.0 and 7.0.0-beta.22

**Comment by bakkot** [comment]
You need parentheses, same as you would for object destructuring without a rest, or for an object literal as a statement by itself.

**Comment by tolmasky** [comment]
Ah, indeed, I guess node REPL auto-wraps and that is why > { ...rest } = {} works.
