### ISSUE TITLE
Flow interfaces & `declare class` do not adhere to ASI

### ISSUE THREAD

**Issue by motiz88** [babel/babylon#733]
### Input Code
```jsx
declare class A {
  foo: boolean
  bar: string
}

declare interface B {
  foo: boolean
  bar: string
}

interface C {
  foo: boolean
  bar: string
}
```

### Babylon/Babel Configuration

```js
{
  "plugins": ["flow"]
}

```

### Expected Behavior
~~~Should parse equivalently to Flow's output (seen [here](http://astexplorer.net/#/gist/e192d3159c84cab0476e372349e41072/15bb1a6573eafe7e9845d043935ffbff21a61531)).~~~

UPDATE: My bad - Flow does emit errors in this case! So Babylon is actually compatible with Flow.

### Current Behavior

Syntax errors on all three declarations, with Babylon expecting a semicolon or comma to separate the properties. 

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  Same behaviour on 6.17.1, 7.0.0-beta.12 and latest `master` a4acf2d

**Comment by hzoo** [comment]
Hey @motiz88! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by motiz88** [comment]
Closing this because Flow actually [does emit errors](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwILwN4Ch7-gHsA7EALngCNDCIQpiBuPAgFwHdCKt5WALOOXjJWMAJbEA5vAC+LfAB94xAK4BbSiBjM5OUEjiJoqeACFs8oqQrVa9YpY5dsvASCEjxU2ZaWqNWji6+tCGEqxaAGZQYAgAwhYEVkK2dAzMSU7croIUnhLSckl+6praQTh64KEI4VExCAAiiQQkKTRpDpmc2fy5wqIFPsXKpYG6dTDRsfAAoi34bTYd9hlsPS597nmD3kUEJQHlE8QRUw3wAGILyct2DI4bPFseu4W+o0cVQA) in this case, and I just missed them in the AST Explorer UI.
