### ISSUE TITLE
Set id to null for ArrowFunctionExpressions?

### ISSUE THREAD

**Issue by EtherTyper** [babel/babylon#747]
Should the [ArrowFunctionExpression section of the AST specification](https://github.com/babel/babylon/blob/master/ast/spec.md#arrowfunctionexpression) clarify that supplying an `Identifier` for `id` does nothing, by explicitly saying `id: null`? Of course, we don't need to change `babel-generator` or `babel-types` to accommodate this change, because that would only hurt backwards compatibility.

Thanks,
Eli

**Comment by hzoo** [comment]
Hey @EtherTyper! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by danez** [comment]
Thanks for opening this issue, would you mind also proposing this to https://github.com/estree/estree. We for the most part use their spec 1:1.
