### ISSUE TITLE
babylon super.xxx will cause performance is very slow

### ISSUE THREAD

**Issue by janryWang** [babel/babylon#750]
This line of code is not perfect , it will replace super.xxx with a very low usage.

https://github.com/babel/babel/blob/master/packages/babel-helper-replace-supers/src/index.js#L31

**Comment by hzoo** [comment]
Hey @janryWang! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by nicolo-ribaudo** [comment]
What do you suggest to make it faster and still correct?
