### ISSUE TITLE
Existential return type annot in arrow function confused with `*=` operator

### ISSUE THREAD

**Issue by mroch** [babel/babylon#772]
### Input Code
```js
const x = ():*=>{}
```

### Babylon/Babel Configuration
flow plugin enabled

### Expected Behavior
Should be an arrow function with a `*` type annotation

### Current Behavior
"Unexpected token" pointing at the `*=`

### Your Environment
babylon7-7.0.0-beta.12 and babylon6-6.17.1: http://astexplorer.net/#/gist/a4d0ae75b6e1db95a394fd591f31a8c9/8cb4469554642dd1ce1bae05742af3146406d8af

Flow parses it correctly

**Comment by hzoo** [comment]
Hey @mroch! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by rajzshkr** [comment]
I can pick this.

**Comment by mroch** [comment]
similar parse error in class fields:

```js
class C { field:*=null }
```

http://astexplorer.net/#/gist/cdceeb9d580e80d636fe107485dc5028/132b56da3acbe567fa46458730dd7875777790c4

**Comment by rajzshkr** [comment]
> similar parse error in class fields:

@mroch can we take this as a separate bug?
