### ISSUE TITLE
Error w/ generics in return type annots inside JSXExpressionContainers

### ISSUE THREAD

**Issue by mroch** [babel/babylon#774]
### Input Code
```js
<bar>{function(): string {}}</bar>; // parses
<bar>{function(): Array<string> {}}</bar>; // errors
```

### Babylon/Babel Configuration
jsx, flow

### Expected Behavior
Flow parses this as a JSXExpressionStatement containing a FunctionExpression containing a GenericTypeAnnotation returnType.

### Current Behavior
Babylon gets into some sort of bad state and errors about unexpected tokens.

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  7.0.0-beta.12
| node             | [astexplorer](http://astexplorer.net/#/gist/a4d0ae75b6e1db95a394fd591f31a8c9/598ba6cf8c988a78535712a88bf28fbb4ecc9640)
| npm              | n/a
| Operating System | Mac

This may be the same as #36. The repro in that issue doesn't seem to work anymore, but there's a test so I'm surprised. Decided to open a new issue since that one is old and closed but happy to move discussion back there.

**Comment by hzoo** [comment]
Hey @mroch! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by nicolo-ribaudo** [comment]
That fix was released in beta.14. Can you try using a more recent version?

**Comment by mroch** [comment]
ah ok. my bad, thanks!
