### ISSUE TITLE
Duplicate definitions of variables should throw syntax error

### ISSUE THREAD

**Issue by danez** [babel/babylon#78]
According to the spec when defining multiple variables with the same name, the parser should throw and SyntaxError when using `let` or `const`:

`let foo, foo;`
or
`let foo; let foo;`

From [13.2.1.1](https://tc39.github.io/ecma262/#sec-let-and-const-declarations-static-semantics-early-errors):

> It is a Syntax Error if the BoundNames of BindingList contains any duplicate entries.

V8 trows an error for `let` and `const`, but not vor `var`.

**Comment by Jamesernator** [comment]
This also causes an error in babel-traverse if it receives one of these invalid asts.
