### ISSUE TITLE
Repeated identifier references in arrays and arguments not replaced.

### ISSUE THREAD

**Issue by jdalton** [babel/babylon#79]
See https://github.com/lodash/babel-plugin-lodash/issues/91.

Despite `binding.referencePaths` being replaced with `path.replaceWith` the resulting code is missing them.
You can see here they are all supposed to be `_noop3.default` and `_range3.default` but some are still `noop` and `_range` instead:
```js
myFunc(_range3.default, _noop3.default);
myFunc(_noop, _noop3.default);
myFunc(_range3.default, _noop, _noop3.default);
myFunc(_range, _noop, _range3.default, _noop3.default);
myFunc(_range, _noop, _range, _noop3.default, _range3.default);

**Comment by danez** [comment]
I don't think this is an issue with babylon. babylon is just parsing code, but not doing any changes to it. This might be better to report here: https://phabricator.babeljs.io/

**Comment by jdalton** [comment]
Moved to https://phabricator.babeljs.io/T7493.
