### ISSUE TITLE
Cannot handle large js file

### ISSUE THREAD

**Issue by lxfind** [babel/babylon#84]
the babylon.js uses `console.log(JSON.stringify(ast, null, "  "));` to dump the ast output, which will run out of memory if the js file is roughly more than 1M (the AST text becomes close to 1G).
It would be nice to provide an option to babylon.js to strip the tokens from the output, as they take up most of the space and are often useless.

**Comment by hzoo** [comment]
I feel like there was an option before? (or maybe that was esprima)

**Comment by RReverser** [comment]
You can also take a look at https://www.npmjs.com/package/JSONStream to avoid memory issues and stall that occurs because `JSON.stringify` tries to serialize entire object into memory.
