### ISSUE TITLE
Inconsistency with semicolons closing decorator statements

### ISSUE THREAD

**Issue by benderTheCrime** [babel/babylon#85]
I noticed that when I have decorated classes, a decorator closed with a semi-colon is a syntax error, while a semi-colon closing a method in a class is acceptable. Here is my .babelrc:

```
{
  "presets": [
    "es2015",
    "es2016",
    "es2017,
    "stage-2"
  ],
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-es2015-block-scoping",
    [
      "transform-es2015-classes",
      {
        "loose": true
      }
    ],
    "transform-proto-to-assign"
  ]
}
```

and an example of the issue to which I am referring:

```
@decorator('foo') // Semi-colon here throws a syntax error on compile
class Bar {
    @decorator('baz'); // Semi-colon here compiles properly
    qux() {}

    @decorator('baz'); // Semi-colon here compiles properly
    static quux() {}
}
```

Admittedly, I do not know enough about the class/property decorators proposal to determine whether or not this is the expected behavior or this is some inconsistency with the AST parser or the `babel-plugin-transform-decorators-legacy` plugin specifically. @loganfsmyth recommended I open an issue here.

**Comment by nicolo-ribaudo** [comment]
Now this correctly throws both using `decorators` and `decorators2`
