### ISSUE TITLE
Does not support 'return + yield ....'

### ISSUE THREAD

**Issue by jakwuh** [babel/babylon#99]
I wonder if such syntax should be supported by babylon. For me such a construction makes sense.
```js
*chooseShowResultsInstantly() {
    return true === yield this.choose({choices: [true, false]})
}
```

**Comment by loganfsmyth** [comment]
This is expected behavior per the spec. You'd get a syntax error from that in all ES6 environments. You'll need to add parens around it, e.g.

    return true === (yield this.choose({choices: [true, false]}))

**Comment by jakwuh** [comment]
Got it, thank you
